# frozen_string_literal: true

module Pangea
  module Resources
    module Akeyless
      include AkeylessArtifactoryTarget
      include AkeylessAssociateRoleAuthMethod
      include AkeylessAuthMethod
      include AkeylessAuthMethodApiKey
      include AkeylessAuthMethodAwsIam
      include AkeylessAuthMethodAzureAd
      include AkeylessAuthMethodCert
      include AkeylessAuthMethodGcp
      include AkeylessAuthMethodK8s
      include AkeylessAuthMethodLdap
      include AkeylessAuthMethodOauth2
      include AkeylessAuthMethodOidc
      include AkeylessAuthMethodSaml
      include AkeylessAuthMethodUniversalIdentity
      include AkeylessAwsTarget
      include AkeylessAzureTarget
      include AkeylessCertificate
      include AkeylessClassicKey
      include AkeylessDbTarget
      include AkeylessDfcKey
      include AkeylessDynamicSecretAws
      include AkeylessDynamicSecretAzure
      include AkeylessDynamicSecretCassandra
      include AkeylessDynamicSecretCustom
      include AkeylessDynamicSecretEks
      include AkeylessDynamicSecretGcp
      include AkeylessDynamicSecretGithub
      include AkeylessDynamicSecretGitlab
      include AkeylessDynamicSecretGke
      include AkeylessDynamicSecretK8s
      include AkeylessDynamicSecretMongo
      include AkeylessDynamicSecretMssql
      include AkeylessDynamicSecretMysql
      include AkeylessDynamicSecretOracle
      include AkeylessDynamicSecretPostgresql
      include AkeylessDynamicSecretRdp
      include AkeylessDynamicSecretRedshift
      include AkeylessEksTarget
      include AkeylessEventForwarderEmail
      include AkeylessEventForwarderServicenow
      include AkeylessEventForwarderSlack
      include AkeylessEventForwarderWebhook
      include AkeylessFolder
      include AkeylessGatewayAllowedAccess
      include AkeylessGatewayCreateK8sAuthConfig
      include AkeylessGatewayProducerArtifactory
      include AkeylessGatewayProducerAws
      include AkeylessGatewayProducerAzure
      include AkeylessGatewayProducerCassandra
      include AkeylessGatewayProducerCustom
      include AkeylessGatewayProducerEks
      include AkeylessGatewayProducerGcp
      include AkeylessGatewayProducerGithub
      include AkeylessGatewayProducerGke
      include AkeylessGatewayProducerK8s
      include AkeylessGatewayProducerMongo
      include AkeylessGatewayProducerMssql
      include AkeylessGatewayProducerMysql
      include AkeylessGatewayProducerOracle
      include AkeylessGatewayProducerPostgresql
      include AkeylessGatewayProducerRdp
      include AkeylessGatewayProducerRedshift
      include AkeylessGatewayRotatedSecret
      include AkeylessGatewayUpdateCache
      include AkeylessGatewayUpdateDefaults
      include AkeylessGatewayUpdateLogForwardingAwsS3
      include AkeylessGatewayUpdateLogForwardingAzureAnalytics
      include AkeylessGatewayUpdateLogForwardingDatadog
      include AkeylessGatewayUpdateLogForwardingElasticsearch
      include AkeylessGatewayUpdateLogForwardingGoogleChronicle
      include AkeylessGatewayUpdateLogForwardingLogstash
      include AkeylessGatewayUpdateLogForwardingLogzIo
      include AkeylessGatewayUpdateLogForwardingSplunk
      include AkeylessGatewayUpdateLogForwardingStdout
      include AkeylessGatewayUpdateLogForwardingSumologic
      include AkeylessGatewayUpdateLogForwardingSyslog
      include AkeylessGatewayUpdateRemoteAccess
      include AkeylessGatewayUpdateRemoteAccessRdpRecording
      include AkeylessGcpTarget
      include AkeylessGithubTarget
      include AkeylessGitlabTarget
      include AkeylessGkeTarget
      include AkeylessGlobalsignTarget
      include AkeylessK8sTarget
      include AkeylessLinkedTarget
      include AkeylessPkiCertIssuer
      include AkeylessRabbitmqTarget
      include AkeylessRole
      include AkeylessRotatedSecretAws
      include AkeylessRotatedSecretAzure
      include AkeylessRotatedSecretCassandra
      include AkeylessRotatedSecretCustom
      include AkeylessRotatedSecretDockerhub
      include AkeylessRotatedSecretGcp
      include AkeylessRotatedSecretHanadb
      include AkeylessRotatedSecretLdap
      include AkeylessRotatedSecretMongo
      include AkeylessRotatedSecretMssql
      include AkeylessRotatedSecretMysql
      include AkeylessRotatedSecretOracle
      include AkeylessRotatedSecretPostgresql
      include AkeylessRotatedSecretRedis
      include AkeylessRotatedSecretRedshift
      include AkeylessRotatedSecretSnowflake
      include AkeylessRotatedSecretSsh
      include AkeylessRotatedSecretSync
      include AkeylessRotatedSecretWindows
      include AkeylessSshCertIssuer
      include AkeylessSshTarget
      include AkeylessStaticSecret
      include AkeylessStaticSecretSync
      include AkeylessTokenizer
      include AkeylessUsc
      include AkeylessUscSecret
      include AkeylessWebTarget
      include AkeylessWindowsTarget
      include AkeylessZerosslTarget
      include DataAkeylessAuth
      include DataAkeylessAuthMethod
      include DataAkeylessCertificate
      include DataAkeylessCsr
      include DataAkeylessDetokenize
      include DataAkeylessDynamicSecret
      include DataAkeylessItems
      include DataAkeylessK8sAuthConfig
      include DataAkeylessKubeExecCreds
      include DataAkeylessPkiCertificate
      include DataAkeylessProducerTmpCreds
      include DataAkeylessResetAccessKey
      include DataAkeylessRole
      include DataAkeylessRotatedSecretValue
      include DataAkeylessRsaPublic
      include DataAkeylessSecret
      include DataAkeylessSshCertificate
      include DataAkeylessStaticSecret
      include DataAkeylessTags
      include DataAkeylessTarget
      include DataAkeylessTargetDetails
      include DataAkeylessTokenize
    end
  end
end
