# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_esm/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessEsm
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_esm,
      attributes_class: Akeyless::Types::EsmAttributes,
      outputs: { id: :id, name: :name },
      map: [:esm_name, :secret_name, :value],
      map_present: [:description, :tags],
      map_bool: [:binary_value]
  end
  module Akeyless
    include AkeylessEsm
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
