# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class DynamicSecretDockerhubAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :delete_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :dockerhub_password, T::String.optional
    attribute? :dockerhub_token_scopes, T::String.optional
    attribute? :dockerhub_username, T::String.optional
    attribute? :item_custom_fields, T::Hash.optional
    attribute :name, T::String
    attribute? :producer_encryption_key_name, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :target_name, T::String.optional
    attribute? :user_ttl, T::String.optional
  end
end
