# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_dynamic_secret_oracle/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessDynamicSecretOracle
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_dynamic_secret_oracle,
      attributes_class: Akeyless::Types::DynamicSecretOracleAttributes,
      outputs: { id: :id, name: :name },
      map: [:name],
      map_present: [:custom_username_template, :db_server_certificates, :db_server_name, :description, :item_custom_fields, :oracle_host, :oracle_password, :oracle_port, :oracle_revocation_statements, :oracle_screation_statements, :oracle_service_name, :oracle_username, :password_length, :producer_encryption_key_name, :tags, :target_name, :user_ttl],
      map_bool: [:delete_protection]
  end
  module Akeyless
    include AkeylessDynamicSecretOracle
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
