# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_producer_aws/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessProducerAws
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_producer_aws,
      attributes_class: Akeyless::Types::ProducerAwsAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:access_mode, :aws_access_key_id, :aws_access_secret_key, :aws_role_arns, :aws_user_groups, :aws_user_policies, :producer_encryption_key_name, :region, :secure_access_aws_account_id, :secure_access_aws_region, :secure_access_bastion_issuer, :secure_access_enable, :secure_access_url, :tags, :target_name, :user_ttl],
      map_bool: [:aws_user_console_access, :aws_user_programmatic_access, :secure_access_aws_native_cli, :secure_access_web, :secure_access_web_browsing]
  end
  module Akeyless
    include AkeylessProducerAws
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
