# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class ProducerAzureAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :name, T::String
    attribute? :app_obj_id, T::String.optional
    attribute? :azure_client_id, T::String.optional
    attribute? :azure_client_secret, T::String.optional
    attribute? :azure_tenant_id, T::String.optional
    attribute? :producer_encryption_key_name, T::String.optional
    attribute? :secure_access_enable, T::String.optional
    attribute? :secure_access_url, T::String.optional
    attribute? :secure_access_web, T::Bool.optional
    attribute? :secure_access_web_browsing, T::Bool.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :target_name, T::String.optional
    attribute? :user_group_obj_id, T::String.optional
    attribute? :user_portal_access, T::Bool.optional
    attribute? :user_principal_name, T::String.optional
    attribute? :user_programmatic_access, T::Bool.optional
    attribute? :user_role_template_id, T::String.optional
    attribute? :user_ttl, T::String.optional
  end
end
