# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_rotated_secret_splunk/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessRotatedSecretSplunk
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_rotated_secret_splunk,
      attributes_class: Akeyless::Types::RotatedSecretSplunkAttributes,
      outputs: { id: :id, name: :name },
      map: [:name, :rotator_type, :target_name],
      map_present: [:audience, :authentication_credentials, :auto_rotate, :description, :expiration_date, :hec_token, :hec_token_name, :key, :max_versions, :password_length, :rotated_password, :rotated_username, :rotation_event_in, :rotation_hour, :rotation_interval, :splunk_token, :tags, :token_owner],
      map_bool: [:delete_protection]
  end
  module Akeyless
    include AkeylessRotatedSecretSplunk
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
