# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class TargetSalesforceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :app_private_key_data, T::String.optional
    attribute :auth_flow, T::String
    attribute? :ca_cert_data, T::String.optional
    attribute? :ca_cert_name, T::String.optional
    attribute :client_id, T::String
    attribute? :client_secret, T::String.optional
    attribute? :description, T::String.optional
    attribute :email, T::String
    attribute? :key, T::String.optional
    attribute? :max_versions, T::String.optional
    attribute :name, T::String
    attribute? :security_token, T::String.optional
    attribute :tenant_url, T::String
  end
end
