# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class DynamicSecretVenafiAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :admin_rotation_interval_days, T::Integer.optional
    attribute? :allow_subdomains, T::Bool.optional
    attribute? :allowed_domains, T::Array.of(T::String).optional
    attribute? :auto_generated_folder, T::String.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :enable_admin_rotation, T::Bool.optional
    attribute? :item_custom_fields, T::Hash.optional
    attribute :name, T::String
    attribute? :producer_encryption_key_name, T::String.optional
    attribute? :root_first_in_chain, T::Bool.optional
    attribute? :sign_using_akeyless_pki, T::Bool.optional
    attribute? :signer_key_name, T::String.optional
    attribute? :store_private_key, T::Bool.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :target_name, T::String.optional
    attribute? :user_ttl, T::String.optional
    attribute? :venafi_access_token, T::String.optional
    attribute? :venafi_api_key, T::String.optional
    attribute? :venafi_baseurl, T::String.optional
    attribute? :venafi_client_id, T::String.optional
    attribute? :venafi_refresh_token, T::String.optional
    attribute? :venafi_use_tpp, T::Bool.optional
    attribute? :venafi_zone, T::String.optional
  end
end
