# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_event_forwarder_webhook/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessEventForwarderWebhook
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_event_forwarder_webhook,
      attributes_class: Akeyless::Types::EventForwarderWebhookAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:auth_methods_event_source_locations, :auth_token, :auth_type, :client_cert_data, :description, :event_types, :every, :gateways_event_source_locations, :items_event_source_locations, :key, :password, :private_key_data, :runner_type, :server_certificates, :targets_event_source_locations, :url, :username]
  end
  module Akeyless
    include AkeylessEventForwarderWebhook
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
