# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_target_globalsign/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessTargetGlobalsign
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_target_globalsign,
      attributes_class: Akeyless::Types::TargetGlobalsignAttributes,
      outputs: { id: :id },
      map: [:contact_email, :contact_first_name, :contact_last_name, :contact_phone, :name, :password, :profile_id, :username],
      map_present: [:description, :key, :timeout]
  end
  module Akeyless
    include AkeylessTargetGlobalsign
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
