# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class TargetGlobalsignAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :contact_email, T::String
    attribute :contact_first_name, T::String
    attribute :contact_last_name, T::String
    attribute :contact_phone, T::String
    attribute :name, T::String
    attribute :password, T::String
    attribute :profile_id, T::String
    attribute :username, T::String
    attribute? :description, T::String.optional
    attribute? :key, T::String.optional
    attribute? :timeout, T::String.optional
  end
end
