# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_gateway_log_forwarding_aws_s3/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessGatewayLogForwardingAwsS3
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_gateway_log_forwarding_aws_s3,
      attributes_class: Akeyless::Types::GatewayLogForwardingAwsS3Attributes,
      outputs: { id: :id },
      map_present: [:access_id, :access_key, :auth_type, :bucket_name, :enable, :log_folder, :output_format, :pull_interval, :region, :role_arn]
  end
  module Akeyless
    include AkeylessGatewayLogForwardingAwsS3
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
