# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_auth_method_gcp/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessAuthMethodGcp
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_auth_method_gcp,
      attributes_class: Akeyless::Types::AuthMethodGcpAttributes,
      outputs: { id: :id },
      map: [:name, :type],
      map_present: [:access_expires, :audience, :audit_logs_claims, :bound_ips, :bound_labels, :bound_projects, :bound_regions, :bound_service_accounts, :bound_zones, :delete_protection, :jwt_ttl, :service_account_creds_data],
      map_bool: [:force_sub_claims]
  end
  module Akeyless
    include AkeylessAuthMethodGcp
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
