# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class AuthMethodGcpAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :name, T::String
    attribute :type, T::String
    attribute? :access_expires, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :audience, T::String.optional
    attribute? :audit_logs_claims, T::Array.of(T::String).optional
    attribute? :bound_ips, T::Array.of(T::String).optional
    attribute? :bound_labels, T::Array.of(T::String).optional
    attribute? :bound_projects, T::Array.of(T::String).optional
    attribute? :bound_regions, T::Array.of(T::String).optional
    attribute? :bound_service_accounts, T::Array.of(T::String).optional
    attribute? :bound_zones, T::Array.of(T::String).optional
    attribute? :delete_protection, T::String.optional
    attribute? :force_sub_claims, T::Bool.optional
    attribute? :jwt_ttl, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :service_account_creds_data, T::String.optional
  end
end
