# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class TargetGcpAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :description, T::String.optional
    attribute? :gcp_key, T::String.optional
    attribute? :key, T::String.optional
    attribute? :max_versions, T::String.optional
    attribute :name, T::String
    attribute? :use_gw_cloud_identity, T::Bool.optional
  end
end
