# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class DynamicSecretGkeAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :delete_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :gke_account_key, T::String.optional
    attribute? :gke_cluster_cert, T::String.optional
    attribute? :gke_cluster_endpoint, T::String.optional
    attribute? :gke_cluster_name, T::String.optional
    attribute? :gke_service_account_email, T::String.optional
    attribute? :item_custom_fields, T::Hash.optional
    attribute :name, T::String
    attribute? :producer_encryption_key_name, T::String.optional
    attribute? :secure_access_allow_port_forwading, T::Bool.optional
    attribute? :secure_access_cluster_endpoint, T::String.optional
    attribute? :secure_access_delay, T::Integer.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :target_name, T::String.optional
    attribute? :user_ttl, T::String.optional
  end
end
