# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_auth_method_email/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessAuthMethodEmail
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_auth_method_email,
      attributes_class: Akeyless::Types::AuthMethodEmailAttributes,
      outputs: { id: :id, name: :name },
      map: [:email, :name],
      map_present: [:access_expires, :allowed_client_type, :audit_logs_claims, :bound_ips, :description, :enable_mfa, :expiration_event_in, :gw_bound_ips, :jwt_ttl, :mfa_type, :product_type],
      map_bool: [:delete_protection, :force_sub_claims]
  end
  module Akeyless
    include AkeylessAuthMethodEmail
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
