# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_dynamic_secret_github/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessDynamicSecretGithub
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_dynamic_secret_github,
      attributes_class: Akeyless::Types::DynamicSecretGithubAttributes,
      outputs: { id: :id, name: :name },
      map: [:name],
      map_present: [:description, :github_app_id, :github_app_private_key, :github_base_url, :installation_id, :installation_organization, :installation_repository, :item_custom_fields, :tags, :target_name, :token_permissions, :token_repositories, :token_ttl],
      map_bool: [:delete_protection]
  end
  module Akeyless
    include AkeylessDynamicSecretGithub
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
