# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class DynamicSecretGoogleWorkspaceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute :access_mode, T::String
    attribute :admin_email, T::String
    attribute? :delete_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :fixed_user_claim_keyname, T::String.optional
    attribute? :gcp_key, T::String.optional
    attribute? :group_email, T::String.optional
    attribute? :group_role, T::String.optional
    attribute? :item_custom_fields, T::Hash.optional
    attribute :name, T::String
    attribute? :producer_encryption_key_name, T::String.optional
    attribute? :role_name, T::String.optional
    attribute? :role_scope, T::String.optional
    attribute? :secure_access_delay, T::Integer.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :target_name, T::String.optional
    attribute? :user_ttl, T::String.optional
  end
end
