# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class ProducerGithubAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :name, T::String
    attribute? :github_app_id, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :github_app_private_key, T::String.optional
    attribute? :github_base_url, T::String.optional
    attribute? :installation_id, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :installation_repository, T::String.optional
    attribute? :target_name, T::String.optional
    attribute? :token_permissions, T::Array.of(T::String).optional
    attribute? :token_repositories, T::Array.of(T::String).optional
  end
end
