# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class TargetRabbitAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :name, T::String
    attribute :rabbitmq_server_uri, T::String
    attribute :rabbitmq_server_user, T::String
    attribute? :description, T::String.optional
    attribute? :key, T::String.optional
    attribute? :rabbitmq_server_password, T::String.optional
  end
end
