# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class DynamicSecretK8sAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :name, T::String
    attribute? :custom_username_template, T::String.optional
    attribute? :delete_protection, T::String.optional
    attribute? :encryption_key_name, T::String.optional
    attribute? :k8s_allowed_namespaces, T::String.optional
    attribute? :k8s_cluster_ca_cert, T::String.optional
    attribute? :k8s_cluster_endpoint, T::String.optional
    attribute? :k8s_cluster_token, T::String.optional
    attribute? :k8s_namespace, T::String.optional
    attribute? :k8s_predefined_role_name, T::String.optional
    attribute? :k8s_predefined_role_type, T::String.optional
    attribute? :k8s_service_account, T::String.optional
    attribute? :k8s_service_account_type, T::String.optional
    attribute? :secure_access_allow_port_forwading, T::Bool.optional
    attribute? :secure_access_bastion_issuer, T::String.optional
    attribute? :secure_access_cluster_endpoint, T::String.optional
    attribute? :secure_access_dashboard_url, T::String.optional
    attribute? :secure_access_enable, T::String.optional
    attribute? :secure_access_web, T::Bool.optional
    attribute? :secure_access_web_browsing, T::Bool.optional
    attribute? :secure_access_web_proxy, T::Bool.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :target_name, T::String.optional
    attribute? :user_ttl, T::String.optional
  end
end
