# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_kmip_environment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessKmipEnvironment
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_kmip_environment,
      attributes_class: Akeyless::Types::KmipEnvironmentAttributes,
      outputs: { id: :id, name: :name },
      map: [:hostname, :root],
      map_present: [:certificate_ttl]
  end
  module Akeyless
    include AkeylessKmipEnvironment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
