# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_dynamic_secret_ldap/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessDynamicSecretLdap
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_dynamic_secret_ldap,
      attributes_class: Akeyless::Types::DynamicSecretLdapAttributes,
      outputs: { id: :id, name: :name },
      map: [:name],
      map_present: [:ProviderType, :bind_dn, :bind_dn_password, :custom_username_template, :description, :external_username, :fixed_user_claim_keyname, :group_dn, :host_provider, :item_custom_fields, :ldap_ca_cert, :ldap_url, :password_length, :producer_encryption_key_name, :secure_access_delay, :secure_access_rd_gateway_server, :tags, :target, :target_name, :token_expiration, :user_attribute, :user_dn, :user_ttl],
      map_bool: [:delete_protection]
  end
  module Akeyless
    include AkeylessDynamicSecretLdap
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
