# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class DynamicSecretCassandraAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :cassandra_creation_statements, T::String.optional
    attribute? :cassandra_hosts, T::String.optional
    attribute? :cassandra_password, T::String.optional
    attribute? :cassandra_port, T::String.optional
    attribute? :cassandra_username, T::String.optional
    attribute? :custom_username_template, T::String.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :item_custom_fields, T::Hash.optional
    attribute :name, T::String
    attribute? :password_length, T::String.optional
    attribute? :producer_encryption_key_name, T::String.optional
    attribute? :ssl, T::Bool.optional
    attribute? :ssl_certificate, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :target_name, T::String.optional
    attribute? :user_ttl, T::String.optional
  end
end
