# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_pki_cert_issuer/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessPkiCertIssuer
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_pki_cert_issuer,
      attributes_class: Akeyless::Types::PkiCertIssuerAttributes,
      outputs: { id: :id },
      map: [:name, :ttl],
      map_present: [:allowed_domains, :allowed_extra_extensions, :allowed_ip_sans, :allowed_uri_sans, :ca_target, :country, :critical_key_usage, :description, :destination_path, :expiration_event_in, :gw_cluster_url, :key_usage, :locality, :organizational_units, :organizations, :postal_code, :province, :scheduled_renew, :signer_key_name, :street_address, :tags],
      map_bool: [:allow_any_name, :allow_copy_ext_from_csr, :allow_subdomains, :auto_renew, :client_flag, :code_signing_flag, :create_private_crl, :create_public_crl, :delete_protection, :enable_acme, :is_ca, :not_enforce_hostnames, :not_require_cn, :protect_certificates, :server_flag]
  end
  module Akeyless
    include AkeylessPkiCertIssuer
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
