# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class PkiCertIssuerAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :name, T::String
    attribute :ttl, T::String
    attribute? :allow_any_name, T::Bool.optional
    attribute? :allow_copy_ext_from_csr, T::Bool.optional
    attribute? :allow_subdomains, T::Bool.optional
    attribute? :allowed_domains, T::String.optional
    attribute? :allowed_extra_extensions, T::String.optional
    attribute? :allowed_ip_sans, T::String.optional
    attribute? :allowed_uri_sans, T::String.optional
    attribute? :auto_renew, T::Bool.optional
    attribute? :ca_target, T::String.optional
    attribute? :client_flag, T::Bool.optional
    attribute? :code_signing_flag, T::Bool.optional
    attribute? :country, T::String.optional
    attribute? :create_private_crl, T::Bool.optional
    attribute? :create_public_crl, T::Bool.optional
    attribute? :critical_key_usage, T::String.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :destination_path, T::String.optional
    attribute? :enable_acme, T::Bool.optional
    attribute? :expiration_event_in, T::Array.of(T::String).optional
    attribute? :gw_cluster_url, T::String.optional
    attribute? :is_ca, T::Bool.optional
    attribute? :key_usage, T::String.optional
    attribute? :locality, T::String.optional
    attribute? :not_enforce_hostnames, T::Bool.optional
    attribute? :not_require_cn, T::Bool.optional
    attribute? :organizational_units, T::String.optional
    attribute? :organizations, T::String.optional
    attribute? :postal_code, T::String.optional
    attribute? :protect_certificates, T::Bool.optional
    attribute? :province, T::String.optional
    attribute? :scheduled_renew, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :server_flag, T::Bool.optional
    attribute? :signer_key_name, T::String.optional
    attribute? :street_address, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
