# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_dynamic_secret_k8s/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessDynamicSecretK8s
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_dynamic_secret_k8s,
      attributes_class: Akeyless::Types::DynamicSecretK8sAttributes,
      outputs: { id: :id, name: :name },
      map: [:name],
      map_present: [:custom_username_template, :description, :item_custom_fields, :k8s_allowed_namespaces, :k8s_cluster_ca_cert, :k8s_cluster_endpoint, :k8s_cluster_name, :k8s_cluster_token, :k8s_namespace, :k8s_predefined_role_name, :k8s_predefined_role_type, :k8s_rolebinding_yaml_data, :k8s_rolebinding_yaml_def, :k8s_service_account, :k8s_service_account_type, :producer_encryption_key_name, :secure_access_cluster_endpoint, :secure_access_dashboard_url, :secure_access_delay, :tags, :target_name, :user_ttl],
      map_bool: [:delete_protection, :secure_access_allow_port_forwading, :use_gw_service_account]
  end
  module Akeyless
    include AkeylessDynamicSecretK8s
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
