# Code generated by pangea-forge.
# InSpec profile for verifying akeyless_k8s_auth_config infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AKEYLESS_TOKEN and AKEYLESS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/akeyless_k8s_auth_config/ -t akeyless://

control 'akeyless_k8s_auth_config-exists' do
  impact 1.0
  title 'Manages a akeyless_k8s_auth_config resource'
  desc 'Verify that the akeyless_k8s_auth_config resource exists and has expected properties'

  describe akeyless_k8s_auth_config(name: attribute('id')) do
    it { should exist }
    its('access_id') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
