# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_target_k8s/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessTargetK8s
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_target_k8s,
      attributes_class: Akeyless::Types::TargetK8sAttributes,
      outputs: { id: :id },
      map: [:k8s_cluster_ca_cert, :k8s_cluster_endpoint, :k8s_cluster_token, :name],
      map_present: [:description, :key]
  end
  module Akeyless
    include AkeylessTargetK8s
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
