# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class TargetK8sAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :k8s_cluster_ca_cert, T::String
    attribute :k8s_cluster_endpoint, T::String
    attribute :k8s_cluster_token, T::String
    attribute :name, T::String
    attribute? :description, T::String.optional
    attribute? :key, T::String.optional
  end
end
