# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class KmipClientAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :activate_keys_on_creation, T::String.optional
    attribute? :certificate_ttl, T::Integer.optional
    attribute :name, T::String
  end
end
