# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class GatewayDefaultsAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute? :cert_access_id, T::String.optional
    attribute? :event_on_status_change, T::String.optional
    attribute? :key, T::String.optional
    attribute? :oidc_access_id, T::String.optional
    attribute? :saml_access_id, T::String.optional
  end
end
