# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_event_forwarder_servicenow/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessEventForwarderServicenow
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_event_forwarder_servicenow,
      attributes_class: Akeyless::Types::EventForwarderServicenowAttributes,
      outputs: { id: :id, name: :name },
      map: [:gateways_event_source_locations, :name, :runner_type],
      map_present: [:admin_name, :admin_pwd, :app_private_key_base64, :auth_methods_event_source_locations, :auth_type, :client_id, :client_secret, :description, :event_types, :every, :host, :items_event_source_locations, :key, :targets_event_source_locations, :user_email]
  end
  module Akeyless
    include AkeylessEventForwarderServicenow
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
