# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class AuthMethodOidcAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :name, T::String
    attribute :unique_identifier, T::String
    attribute? :access_expires, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :allowed_redirect_uri, T::Array.of(T::String).optional
    attribute? :audit_logs_claims, T::Array.of(T::String).optional
    attribute? :bound_ips, T::Array.of(T::String).optional
    attribute? :client_id, T::String.optional
    attribute? :client_secret, T::String.optional
    attribute? :delete_protection, T::String.optional
    attribute? :force_sub_claims, T::Bool.optional
    attribute? :issuer, T::String.optional
    attribute? :jwt_ttl, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :required_scopes, T::Array.of(T::String).optional
    attribute? :required_scopes_prefix, T::String.optional
  end
end
