# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_target_godaddy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessTargetGodaddy
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_target_godaddy,
      attributes_class: Akeyless::Types::TargetGodaddyAttributes,
      outputs: { id: :id, name: :name },
      map: [:api_key, :imap_fqdn, :imap_password, :imap_username, :name, :secret],
      map_present: [:customer_id, :description, :imap_port, :key, :max_versions, :timeout]
  end
  module Akeyless
    include AkeylessTargetGodaddy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
