# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_dynamic_secret_aws/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessDynamicSecretAws
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_dynamic_secret_aws,
      attributes_class: Akeyless::Types::DynamicSecretAwsAttributes,
      outputs: { id: :id, name: :name },
      map: [:name],
      map_present: [:access_mode, :admin_rotation_interval_days, :aws_access_key_id, :aws_access_secret_key, :aws_external_id, :aws_role_arns, :aws_user_groups, :aws_user_policies, :custom_username_template, :description, :item_custom_fields, :password_length, :producer_encryption_key_name, :region, :secure_access_delay, :session_tags, :tags, :target_name, :transitive_tag_keys, :user_ttl],
      map_bool: [:aws_user_console_access, :aws_user_programmatic_access, :delete_protection, :enable_admin_rotation]
  end
  module Akeyless
    include AkeylessDynamicSecretAws
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
