# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class DynamicSecretAwsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :access_mode, T::String.optional
    attribute? :admin_rotation_interval_days, T::Integer.optional
    attribute? :aws_access_key_id, T::String.optional
    attribute? :aws_access_secret_key, T::String.optional
    attribute? :aws_external_id, T::String.optional
    attribute? :aws_role_arns, T::String.optional
    attribute? :aws_user_console_access, T::Bool.optional
    attribute? :aws_user_groups, T::String.optional
    attribute? :aws_user_policies, T::String.optional
    attribute? :aws_user_programmatic_access, T::Bool.optional
    attribute? :custom_username_template, T::String.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :enable_admin_rotation, T::Bool.optional
    attribute? :item_custom_fields, T::Hash.optional
    attribute :name, T::String
    attribute? :password_length, T::String.optional
    attribute? :producer_encryption_key_name, T::String.optional
    attribute? :region, T::String.optional
    attribute? :secure_access_delay, T::Integer.optional
    attribute? :session_tags, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :target_name, T::String.optional
    attribute? :transitive_tag_keys, T::String.optional
    attribute? :user_ttl, T::String.optional
  end
end
