# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_rotated_secret_azure/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessRotatedSecretAzure
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_rotated_secret_azure,
      attributes_class: Akeyless::Types::RotatedSecretAzureAttributes,
      outputs: { id: :id },
      map: [:name, :rotator_type, :target_name],
      map_present: [:api_id, :api_key, :app_id, :authentication_credentials, :auto_rotate, :description, :key, :password_length, :rotation_hour, :rotation_interval, :storage_account_key_name, :tags, :username]
  end
  module Akeyless
    include AkeylessRotatedSecretAzure
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
