# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_event_forwarder_service_now/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessEventForwarderServiceNow
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_event_forwarder_service_now,
      attributes_class: Akeyless::Types::EventForwarderServiceNowAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:admin_name, :admin_pwd, :app_private_key_base64, :auth_methods_event_source_locations, :auth_type, :client_id, :client_secret, :description, :event_types, :every, :gateways_event_source_locations, :host, :items_event_source_locations, :key, :runner_type, :targets_event_source_locations, :user_email]
  end
  module Akeyless
    include AkeylessEventForwarderServiceNow
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
