# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class EventForwarderServiceNowAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :name, T::String
    attribute? :admin_name, T::String.optional
    attribute? :admin_pwd, T::String.optional
    attribute? :app_private_key_base64, T::String.optional
    attribute? :auth_methods_event_source_locations, T::Array.of(T::String).optional
    attribute? :auth_type, T::String.optional
    attribute? :client_id, T::String.optional
    attribute? :client_secret, T::String.optional
    attribute? :description, T::String.optional
    attribute? :event_types, T::Array.of(T::String).optional
    attribute? :every, T::String.optional
    attribute? :gateways_event_source_locations, T::Array.of(T::String).optional
    attribute? :host, T::String.optional
    attribute? :items_event_source_locations, T::Array.of(T::String).optional
    attribute? :key, T::String.optional
    attribute? :runner_type, T::String.optional
    attribute? :targets_event_source_locations, T::Array.of(T::String).optional
    attribute? :user_email, T::String.optional
  end
end
