# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_dynamic_secret_mysql/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessDynamicSecretMysql
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_dynamic_secret_mysql,
      attributes_class: Akeyless::Types::DynamicSecretMysqlAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:custom_username_template, :db_server_certificates, :db_server_name, :encryption_key_name, :mysql_creation_statements, :mysql_dbname, :mysql_host, :mysql_password, :mysql_port, :mysql_revocation_statements, :mysql_username, :password_length, :secure_access_bastion_issuer, :secure_access_db_name, :secure_access_enable, :secure_access_host, :ssl_certificate, :tags, :target_name, :user_ttl],
      map_bool: [:secure_access_web, :ssl]
  end
  module Akeyless
    include AkeylessDynamicSecretMysql
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
