# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class DynamicSecretMysqlAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :custom_username_template, T::String.optional
    attribute? :db_server_certificates, T::String.optional
    attribute? :db_server_name, T::String.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :item_custom_fields, T::Hash.optional
    attribute? :mysql_dbname, T::String.optional
    attribute? :mysql_host, T::String.optional
    attribute? :mysql_password, T::String.optional
    attribute? :mysql_port, T::String.optional
    attribute? :mysql_revocation_statements, T::String.optional
    attribute? :mysql_screation_statements, T::String.optional
    attribute? :mysql_username, T::String.optional
    attribute :name, T::String
    attribute? :password_length, T::String.optional
    attribute? :producer_encryption_key_name, T::String.optional
    attribute? :secure_access_delay, T::Integer.optional
    attribute? :ssl, T::Bool.optional
    attribute? :ssl_certificate, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :target_name, T::String.optional
    attribute? :user_ttl, T::String.optional
  end
end
