# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class GatewayLogForwardingGoogleChronicleAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute? :customer_id, T::String.optional
    attribute? :enable, T::String.optional
    attribute? :gcp_key, T::String.optional
    attribute? :log_type, T::String.optional
    attribute? :output_format, T::String.optional
    attribute? :pull_interval, T::String.optional
    attribute? :region, T::String.optional
  end
end
