# Code generated by pangea-forge.
# InSpec profile for verifying akeyless_gateway_defaults infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AKEYLESS_TOKEN and AKEYLESS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/akeyless_gateway_defaults/ -t akeyless://

control 'akeyless_gateway_defaults-exists' do
  impact 1.0
  title 'Manages a akeyless_gateway_defaults resource'
  desc 'Verify that the akeyless_gateway_defaults resource exists and has expected properties'

  describe akeyless_gateway_defaults(name: attribute('id')) do
    it { should exist }
  end
end
