# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_target_hashi_vault/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessTargetHashiVault
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_target_hashi_vault,
      attributes_class: Akeyless::Types::TargetHashiVaultAttributes,
      outputs: { id: :id, name: :name },
      map: [:name],
      map_present: [:description, :hashi_url, :key, :max_versions, :namespace, :vault_token]
  end
  module Akeyless
    include AkeylessTargetHashiVault
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
