# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_target_rabbitmq/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessTargetRabbitmq
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_target_rabbitmq,
      attributes_class: Akeyless::Types::TargetRabbitmqAttributes,
      outputs: { id: :id, name: :name },
      map: [:name],
      map_present: [:description, :key, :max_versions, :rabbitmq_server_password, :rabbitmq_server_uri, :rabbitmq_server_user]
  end
  module Akeyless
    include AkeylessTargetRabbitmq
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
