# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_target_zerossl/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessTargetZerossl
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_target_zerossl,
      attributes_class: Akeyless::Types::TargetZerosslAttributes,
      outputs: { id: :id },
      map: [:api_key, :imap_fqdn, :imap_password, :imap_username, :name],
      map_present: [:description, :imap_port, :imap_target_email, :key, :timeout]
  end
  module Akeyless
    include AkeylessTargetZerossl
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
