# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class TargetLdapAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute :bind_dn, T::String
    attribute :bind_dn_password, T::String
    attribute? :description, T::String.optional
    attribute? :key, T::String.optional
    attribute? :ldap_ca_cert, T::String.optional
    attribute :ldap_url, T::String
    attribute? :max_versions, T::String.optional
    attribute :name, T::String
    attribute? :server_type, T::String.optional
    attribute? :token_expiration, T::String.optional
  end
end
