# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class AuthMethodOauth2Attributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :access_expires, T::Integer.optional
    attribute? :allowed_client_type, T::Array.of(T::String).optional
    attribute? :audience, T::String.optional
    attribute? :audit_logs_claims, T::Array.of(T::String).optional
    attribute? :bound_client_ids, T::Array.of(T::String).optional
    attribute? :bound_ips, T::Array.of(T::String).optional
    attribute? :cert, T::String.optional
    attribute? :cert_file_data, T::String.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :expiration_event_in, T::Array.of(T::String).optional
    attribute? :force_sub_claims, T::Bool.optional
    attribute? :gateway_url, T::String.optional
    attribute? :gw_bound_ips, T::Array.of(T::String).optional
    attribute? :issuer, T::String.optional
    attribute? :jwks_json_data, T::String.optional
    attribute? :jwks_uri, T::String.optional
    attribute? :jwt_ttl, T::Integer.optional
    attribute :name, T::String
    attribute? :product_type, T::Array.of(T::String).optional
    attribute? :subclaims_delimiters, T::Array.of(T::String).optional
    attribute :unique_identifier, T::String
  end
end
