# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class ProducerGcpAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :name, T::String
    attribute? :delete_protection, T::String.optional
    attribute? :gcp_cred_type, T::String.optional
    attribute? :gcp_key, T::String.optional
    attribute? :gcp_key_algo, T::String.optional
    attribute? :gcp_sa_email, T::String.optional
    attribute? :gcp_token_scopes, T::String.optional
    attribute? :producer_encryption_key_name, T::String.optional
    attribute? :role_binding, T::String.optional
    attribute? :service_account_type, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :target_name, T::String.optional
    attribute? :user_ttl, T::String.optional
  end
end
