# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class DfcKeyAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :alg, T::String
    attribute :name, T::String
    attribute? :auto_rotate, T::String.optional
    attribute? :cert_data_base64, T::String.optional
    attribute? :certificate_common_name, T::String.optional
    attribute? :certificate_country, T::String.optional
    attribute? :certificate_format, T::String.optional
    attribute? :certificate_locality, T::String.optional
    attribute? :certificate_organization, T::String.optional
    attribute? :certificate_province, T::String.optional
    attribute? :certificate_ttl, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :conf_file_data, T::String.optional
    attribute? :customer_frg_id, T::String.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :expiration_event_in, T::Array.of(T::String).optional
    attribute? :generate_self_signed_certificate, T::Bool.optional
    attribute? :rotation_event_in, T::Array.of(T::String).optional
    attribute? :rotation_interval, T::String.optional
    attribute? :split_level, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
