# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class DfcKeyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute :alg, T::String
    attribute? :auto_rotate, T::String.optional
    attribute? :certificate_common_name, T::String.optional
    attribute? :certificate_country, T::String.optional
    attribute? :certificate_digest_algo, T::String.optional
    attribute? :certificate_format, T::String.optional
    attribute? :certificate_locality, T::String.optional
    attribute? :certificate_organization, T::String.optional
    attribute? :certificate_province, T::String.optional
    attribute? :certificate_ttl, T::Integer.optional
    attribute? :customer_frg_id, T::String.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :expiration_event_in, T::Array.of(T::String).optional
    attribute? :generate_self_signed_certificate, T::Bool.optional
    attribute? :hash_algorithm, T::String.optional
    attribute? :item_custom_fields, T::Hash.optional
    attribute :name, T::String
    attribute? :rotation_event_in, T::Array.of(T::String).optional
    attribute? :rotation_interval, T::String.optional
    attribute? :split_level, T::Integer.optional
    attribute? :tag, T::Array.of(T::String).optional
  end
end
