# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class DynamicSecretHanadbAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :custom_username_template, T::String.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :hana_dbname, T::String.optional
    attribute? :hanadb_create_statements, T::String.optional
    attribute? :hanadb_host, T::String.optional
    attribute? :hanadb_password, T::String.optional
    attribute? :hanadb_port, T::String.optional
    attribute? :hanadb_revocation_statements, T::String.optional
    attribute? :hanadb_username, T::String.optional
    attribute? :item_custom_fields, T::Hash.optional
    attribute :name, T::String
    attribute? :password_length, T::String.optional
    attribute? :producer_encryption_key_name, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :target_name, T::String.optional
    attribute? :user_ttl, T::String.optional
  end
end
