# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_target_eks/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessTargetEks
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_target_eks,
      attributes_class: Akeyless::Types::TargetEksAttributes,
      outputs: { id: :id, name: :name },
      map: [:eks_access_key_id, :eks_cluster_ca_cert, :eks_cluster_endpoint, :eks_cluster_name, :eks_secret_access_key, :name],
      map_present: [:description, :eks_region, :key, :max_versions],
      map_bool: [:use_gw_cloud_identity]
  end
  module Akeyless
    include AkeylessTargetEks
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
