# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_producer_rdp/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessProducerRdp
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_producer_rdp,
      attributes_class: Akeyless::Types::ProducerRdpAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:fixed_user_only, :producer_encryption_key_name, :rdp_admin_name, :rdp_admin_pwd, :rdp_host_name, :rdp_host_port, :rdp_user_groups, :secure_access_enable, :secure_access_host, :secure_access_rdp_domain, :secure_access_rdp_user, :tags, :target_name, :user_ttl],
      map_bool: [:secure_access_allow_external_user, :secure_access_web]
  end
  module Akeyless
    include AkeylessProducerRdp
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
