# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class DynamicSecretRdpAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :allow_user_extend_session, T::Integer.optional
    attribute? :custom_username_template, T::String.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :fixed_user_claim_keyname, T::String.optional
    attribute? :fixed_user_only, T::String.optional
    attribute? :item_custom_fields, T::Hash.optional
    attribute :name, T::String
    attribute? :password_length, T::String.optional
    attribute? :producer_encryption_key_name, T::String.optional
    attribute? :rdp_admin_name, T::String.optional
    attribute? :rdp_admin_pwd, T::String.optional
    attribute? :rdp_host_name, T::String.optional
    attribute? :rdp_host_port, T::String.optional
    attribute? :rdp_user_groups, T::String.optional
    attribute? :secure_access_delay, T::Integer.optional
    attribute? :secure_access_rd_gateway_server, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :target_name, T::String.optional
    attribute? :user_ttl, T::String.optional
    attribute? :warn_user_before_expiration, T::Integer.optional
  end
end
