# Code generated by pangea-forge.
# InSpec profile for verifying akeyless_static_secret_sync infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AKEYLESS_TOKEN and AKEYLESS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/akeyless_static_secret_sync/ -t akeyless://

control 'akeyless_static_secret_sync-exists' do
  impact 1.0
  title 'Manages a akeyless_static_secret_sync resource'
  desc 'Verify that the akeyless_static_secret_sync resource exists and has expected properties'

  describe akeyless_static_secret_sync(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
    its('remote_secret_name') { should_not be_nil }
    its('usc_name') { should_not be_nil }
  end
end
