# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_target_ssh/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessTargetSsh
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_target_ssh,
      attributes_class: Akeyless::Types::TargetSshAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:description, :host, :key, :port, :private_key, :private_key_password, :ssh_password, :ssh_username]
  end
  module Akeyless
    include AkeylessTargetSsh
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
