# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class RotatedSecretAwsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :api_id, T::String.optional
    attribute? :api_key, T::String.optional
    attribute? :authentication_credentials, T::String.optional
    attribute? :auto_rotate, T::String.optional
    attribute? :aws_region, T::String.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :grace_rotation, T::String.optional
    attribute? :grace_rotation_hour, T::Integer.optional
    attribute? :grace_rotation_interval, T::String.optional
    attribute? :grace_rotation_timing, T::String.optional
    attribute? :key, T::String.optional
    attribute? :max_versions, T::String.optional
    attribute :name, T::String
    attribute? :password_length, T::String.optional
    attribute? :rotate_after_disconnect, T::String.optional
    attribute? :rotation_event_in, T::Array.of(T::String).optional
    attribute? :rotation_hour, T::Integer.optional
    attribute? :rotation_interval, T::String.optional
    attribute :rotator_type, T::String
    attribute? :tags, T::Array.of(T::String).optional
    attribute :target_name, T::String
  end
end
