# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_static_secret/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessStaticSecret
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_static_secret,
      attributes_class: Akeyless::Types::StaticSecretAttributes,
      outputs: { id: :id, name: :name },
      map: [:name, :value],
      map_present: [:accessibility, :description, :format, :max_versions, :protection_key, :tags, :type],
      map_bool: [:delete_protection]
  end
  module Akeyless
    include AkeylessStaticSecret
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
