# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_rotated_secret_aws/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessRotatedSecretAws
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_rotated_secret_aws,
      attributes_class: Akeyless::Types::RotatedSecretAwsAttributes,
      outputs: { id: :id, name: :name },
      map: [:name, :rotator_type, :target_name],
      map_present: [:api_id, :api_key, :authentication_credentials, :auto_rotate, :aws_region, :description, :grace_rotation, :grace_rotation_hour, :grace_rotation_interval, :grace_rotation_timing, :key, :max_versions, :password_length, :rotate_after_disconnect, :rotation_event_in, :rotation_hour, :rotation_interval, :tags],
      map_bool: [:delete_protection]
  end
  module Akeyless
    include AkeylessRotatedSecretAws
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
