# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class RoleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :analytics_access, T::String.optional
    attribute? :audit_access, T::String.optional
    attribute? :comment, T::String.optional
    attribute? :delete_protection, T::String.optional
    attribute? :description, T::String.optional
    attribute? :event_center_access, T::String.optional
    attribute? :event_forwarders_access, T::String.optional
    attribute? :event_forwarders_name, T::Array.of(T::String).optional
    attribute? :gw_analytics_access, T::String.optional
    attribute :name, T::String
    attribute? :reverse_rbac_access, T::String.optional
    attribute? :sra_reports_access, T::String.optional
    attribute? :usage_reports_access, T::String.optional
  end
end
