# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class RoleAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :name, T::String
    attribute? :analytics_access, T::String.optional
    attribute? :assoc_auth_method, T::Array.of(T::Hash).optional
    attribute? :audit_access, T::String.optional
    attribute? :delete_protection, T::String.optional
    attribute? :description, T::String.optional
    attribute? :event_center_access, T::String.optional
    attribute? :event_forwarders_access, T::String.optional
    attribute? :gw_analytics_access, T::String.optional
    attribute? :rules, T::Array.of(T::Hash).optional
    attribute? :sra_reports_access, T::String.optional
    attribute? :usage_reports_access, T::String.optional
  end
end
