# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_dynamic_secret_gke/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessDynamicSecretGke
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_dynamic_secret_gke,
      attributes_class: Akeyless::Types::DynamicSecretGkeAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:encryption_key_name, :gke_account_key, :gke_cluster_cert, :gke_cluster_endpoint, :gke_cluster_name, :gke_service_account_email, :secure_access_bastion_issuer, :secure_access_cluster_endpoint, :secure_access_enable, :tags, :target_name, :user_ttl],
      map_bool: [:secure_access_allow_port_forwading, :secure_access_web]
  end
  module Akeyless
    include AkeylessDynamicSecretGke
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
