# Code generated by pangea-forge.
# InSpec profile for verifying akeyless_folder infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AKEYLESS_TOKEN and AKEYLESS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/akeyless_folder/ -t akeyless://

control 'akeyless_folder-exists' do
  impact 1.0
  title 'Manages a akeyless_folder resource'
  desc 'Verify that the akeyless_folder resource exists and has expected properties'

  describe akeyless_folder(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
  end
end
