# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class DynamicSecretMongodbAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :name, T::String
    attribute? :custom_username_template, T::String.optional
    attribute? :encryption_key_name, T::String.optional
    attribute? :mongodb_atlas_api_private_key, T::String.optional
    attribute? :mongodb_atlas_api_public_key, T::String.optional
    attribute? :mongodb_atlas_project_id, T::String.optional
    attribute? :mongodb_default_auth_db, T::String.optional
    attribute? :mongodb_host_port, T::String.optional
    attribute? :mongodb_name, T::String.optional
    attribute? :mongodb_password, T::String.optional
    attribute? :mongodb_roles, T::String.optional
    attribute? :mongodb_server_uri, T::String.optional
    attribute? :mongodb_uri_options, T::String.optional
    attribute? :mongodb_username, T::String.optional
    attribute? :password_length, T::String.optional
    attribute? :secure_access_bastion_issuer, T::String.optional
    attribute? :secure_access_db_name, T::String.optional
    attribute? :secure_access_enable, T::String.optional
    attribute? :secure_access_host, T::Array.of(T::String).optional
    attribute? :secure_access_web, T::Bool.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :target_name, T::String.optional
    attribute? :user_ttl, T::String.optional
  end
end
