# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class CertificateAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :name, T::String
    attribute? :certificate_data, T::String.optional
    attribute? :delete_protection, T::String.optional
    attribute? :description, T::String.optional
    attribute? :expiration_event_in, T::Array.of(T::String).optional
    attribute? :format, T::String.optional
    attribute? :key, T::String.optional
    attribute? :key_data, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
