# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class SshCertIssuerAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :ProviderType, T::String.optional
    attribute :allowed_users, T::String
    attribute? :delete_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :extensions, T::Hash.optional
    attribute? :external_username, T::String.optional
    attribute? :fixed_user_claim_keyname, T::String.optional
    attribute? :host_provider, T::String.optional
    attribute :name, T::String
    attribute? :principals, T::String.optional
    attribute? :secure_access_use_internal_ssh_access, T::Bool.optional
    attribute :signer_key_name, T::String
    attribute? :tag, T::Array.of(T::String).optional
    attribute? :target, T::Array.of(T::String).optional
    attribute :ttl, T::Integer
  end
end
