# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_folder/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessFolder
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_folder,
      attributes_class: Akeyless::Types::FolderAttributes,
      outputs: { id: :id, name: :name },
      map: [:name],
      map_present: [:accessibility, :description, :tags, :type],
      map_bool: [:delete_protection]
  end
  module Akeyless
    include AkeylessFolder
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
