# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_target_gitlab/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessTargetGitlab
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_target_gitlab,
      attributes_class: Akeyless::Types::TargetGitlabAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:description, :gitlab_access_token, :gitlab_certificate, :gitlab_url, :key]
  end
  module Akeyless
    include AkeylessTargetGitlab
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
