# Code generated by pangea-forge.
# InSpec profile for verifying akeyless_target_k8s infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AKEYLESS_TOKEN and AKEYLESS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/akeyless_target_k8s/ -t akeyless://

control 'akeyless_target_k8s-exists' do
  impact 1.0
  title 'Manages a akeyless_target_k8s resource'
  desc 'Verify that the akeyless_target_k8s resource exists and has expected properties'

  describe akeyless_target_k8s(name: attribute('id')) do
    it { should exist }
    its('k8s_cluster_endpoint') { should_not be_nil }
    its('k8s_cluster_token') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
