# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_target_db/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessTargetDb
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_target_db,
      attributes_class: Akeyless::Types::TargetDbAttributes,
      outputs: { id: :id, name: :name },
      map: [:connection_type, :db_type, :name],
      map_present: [:azure_client_id, :azure_client_secret, :azure_tenant_id, :cloud_service_provider, :comment, :db_name, :db_server_certificates, :db_server_name, :description, :host, :key, :max_versions, :mongodb_atlas_api_private_key, :mongodb_atlas_api_public_key, :mongodb_atlas_project_id, :mongodb_default_auth_db, :mongodb_uri_options, :oracle_service_name, :oracle_wallet_login_type, :oracle_wallet_p12_file_data, :oracle_wallet_sso_file_data, :parent_target_name, :port, :pwd, :snowflake_account, :snowflake_api_private_key, :snowflake_api_private_key_password, :ssl_certificate, :user_name],
      map_bool: [:cluster_mode, :mongodb_atlas, :ssl]
  end
  module Akeyless
    include AkeylessTargetDb
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
