# Code generated by pangea-forge.
# InSpec profile for verifying akeyless_auth_method_ldap infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AKEYLESS_TOKEN and AKEYLESS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/akeyless_auth_method_ldap/ -t akeyless://

control 'akeyless_auth_method_ldap-exists' do
  impact 1.0
  title 'Manages a akeyless_auth_method_ldap resource'
  desc 'Verify that the akeyless_auth_method_ldap resource exists and has expected properties'

  describe akeyless_auth_method_ldap(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
  end
end
