# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_static_secret_sync/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessStaticSecretSync
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_static_secret_sync,
      attributes_class: Akeyless::Types::StaticSecretSyncAttributes,
      outputs: { id: :id },
      map: [:name, :remote_secret_name, :usc_name],
      map_present: [:filter_secret_value, :namespace]
  end
  module Akeyless
    include AkeylessStaticSecretSync
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
