# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_k8s_auth_config/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessK8sAuthConfig
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_k8s_auth_config,
      attributes_class: Akeyless::Types::K8sAuthConfigAttributes,
      outputs: { id: :id },
      map: [:access_id, :name],
      map_present: [:cluster_api_type, :disable_issuer_validation, :k8s_auth_type, :k8s_ca_cert, :k8s_client_certificate, :k8s_client_key, :k8s_host, :k8s_issuer, :rancher_api_key, :rancher_cluster_id, :signing_key, :token_exp, :token_reviewer_jwt],
      map_bool: [:use_local_ca_jwt]
  end
  module Akeyless
    include AkeylessK8sAuthConfig
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
