# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_associate_role_auth_method/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessAssociateRoleAuthMethod
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_associate_role_auth_method,
      attributes_class: Akeyless::Types::AssociateRoleAuthMethodAttributes,
      outputs: { id: :id },
      map: [:am_name, :role_name],
      map_present: [:case_sensitive, :sub_claims]
  end
  module Akeyless
    include AkeylessAssociateRoleAuthMethod
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
