# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_role_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessRoleRule
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_role_rule,
      attributes_class: Akeyless::Types::RoleRuleAttributes,
      outputs: { id: :id, name: :name },
      map: [:capability, :path, :role_name],
      map_present: [:rule_type, :ttl]
  end
  module Akeyless
    include AkeylessRoleRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
