# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class TargetLetsEncryptAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :acme_challenge, T::String.optional
    attribute? :description, T::String.optional
    attribute? :dns_target_creds, T::String.optional
    attribute? :email, T::String.optional
    attribute? :gcp_project, T::String.optional
    attribute? :hosted_zone, T::String.optional
    attribute? :key, T::String.optional
    attribute? :lets_encrypt_url, T::String.optional
    attribute? :max_versions, T::String.optional
    attribute :name, T::String
    attribute? :resource_group, T::String.optional
    attribute? :timeout, T::String.optional
  end
end
