# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class UscAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :name, T::String
    attribute :target_to_associate, T::String
    attribute? :azure_kv_name, T::String.optional
    attribute? :delete_protection, T::String.optional
    attribute? :description, T::String.optional
    attribute? :k8s_namespace, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
