# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class EventForwarderEmailAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :auth_methods_event_source_locations, T::Array.of(T::String).optional
    attribute? :description, T::String.optional
    attribute? :email_to, T::String.optional
    attribute? :event_types, T::Array.of(T::String).optional
    attribute? :every, T::String.optional
    attribute :gateways_event_source_locations, T::Array.of(T::String)
    attribute? :include_error, T::String.optional
    attribute? :items_event_source_locations, T::Array.of(T::String).optional
    attribute? :key, T::String.optional
    attribute :name, T::String
    attribute? :override_url, T::String.optional
    attribute :runner_type, T::String
    attribute? :targets_event_source_locations, T::Array.of(T::String).optional
  end
end
