# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_target_web/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessTargetWeb
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_target_web,
      attributes_class: Akeyless::Types::TargetWebAttributes,
      outputs: { id: :id, name: :name },
      map: [:name],
      map_present: [:description, :key, :max_versions, :url]
  end
  module Akeyless
    include AkeylessTargetWeb
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
