# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_auth_method_huawei/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessAuthMethodHuawei
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_auth_method_huawei,
      attributes_class: Akeyless::Types::AuthMethodHuaweiAttributes,
      outputs: { id: :id, name: :name },
      map: [:name],
      map_present: [:access_expires, :allowed_client_type, :audit_logs_claims, :auth_url, :bound_domain_id, :bound_domain_name, :bound_ips, :bound_tenant_id, :bound_tenant_name, :bound_user_id, :bound_user_name, :delete_protection, :description, :expiration_event_in, :gw_bound_ips, :jwt_ttl, :product_type],
      map_bool: [:force_sub_claims]
  end
  module Akeyless
    include AkeylessAuthMethodHuawei
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
