# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessRotatedSecretMysql do
  describe ':akeyless_rotated_secret_mysql' do
    it 'synthesizes valid Terraform JSON' do
      pending 'implement synthesis test'
    end
  end
end
