# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_dynamic_secret_snowflake/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessDynamicSecretSnowflake
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_dynamic_secret_snowflake,
      attributes_class: Akeyless::Types::DynamicSecretSnowflakeAttributes,
      outputs: { id: :id, name: :name },
      map: [:name],
      map_present: [:account, :account_password, :account_username, :auth_mode, :custom_username_template, :db_name, :description, :item_custom_fields, :key_algo, :password_length, :private_key, :private_key_passphrase, :role, :tags, :target_name, :user_ttl, :warehouse],
      map_bool: [:delete_protection]
  end
  module Akeyless
    include AkeylessDynamicSecretSnowflake
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
