# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class TargetWindowsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :certificate, T::String.optional
    attribute? :connection_type, T::String.optional
    attribute? :description, T::String.optional
    attribute? :domain, T::String.optional
    attribute :hostname, T::String
    attribute? :key, T::String.optional
    attribute? :max_versions, T::String.optional
    attribute :name, T::String
    attribute? :parent_target_name, T::String.optional
    attribute? :port, T::String.optional
    attribute? :use_tls, T::Bool.optional
  end
end
