# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_producer_cassandra/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessProducerCassandra
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_producer_cassandra,
      attributes_class: Akeyless::Types::ProducerCassandraAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:cassandra_creation_statements, :cassandra_hosts, :cassandra_password, :cassandra_port, :cassandra_username, :producer_encryption_key_name, :tags, :target_name, :user_ttl]
  end
  module Akeyless
    include AkeylessProducerCassandra
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
