# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/akeyless_types'

module Pangea::Resources::Akeyless::Types
  class TargetOpenaiAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Akeyless::Types

    attribute? :api_key, T::String.optional
    attribute? :api_key_id, T::String.optional
    attribute? :description, T::String.optional
    attribute? :key, T::String.optional
    attribute? :max_versions, T::String.optional
    attribute? :model, T::String.optional
    attribute :name, T::String
    attribute? :openai_url, T::String.optional
    attribute? :organization_id, T::String.optional
  end
end
