# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class TargetArtifactoryAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :artifactory_admin_name, T::String
    attribute :artifactory_admin_pwd, T::String
    attribute :base_url, T::String
    attribute :name, T::String
    attribute? :description, T::String.optional
    attribute? :key, T::String.optional
  end
end
