# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_dynamic_secret_artifactory/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessDynamicSecretArtifactory
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_dynamic_secret_artifactory,
      attributes_class: Akeyless::Types::DynamicSecretArtifactoryAttributes,
      outputs: { id: :id },
      map: [:artifactory_token_audience, :artifactory_token_scope, :name],
      map_present: [:artifactory_admin_name, :artifactory_admin_pwd, :base_url, :custom_username_template, :encryption_key_name, :tags, :target_name, :user_ttl]
  end
  module Akeyless
    include AkeylessDynamicSecretArtifactory
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
