# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class AuthMethodK8sAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :name, T::String
    attribute? :access_expires, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :audience, T::String.optional
    attribute? :audit_logs_claims, T::Array.of(T::String).optional
    attribute? :bound_ips, T::Array.of(T::String).optional
    attribute? :bound_namespaces, T::Array.of(T::String).optional
    attribute? :bound_pod_names, T::Array.of(T::String).optional
    attribute? :bound_sa_names, T::Array.of(T::String).optional
    attribute? :delete_protection, T::String.optional
    attribute? :force_sub_claims, T::Bool.optional
    attribute? :gen_key, T::String.optional
    attribute? :jwt_ttl, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :public_key, T::String.optional
  end
end
