# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_target_splunk/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessTargetSplunk
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_target_splunk,
      attributes_class: Akeyless::Types::TargetSplunkAttributes,
      outputs: { id: :id, name: :name },
      map: [:name, :url],
      map_present: [:audience, :description, :key, :max_versions, :token_owner],
      map_bool: [:use_tls]
  end
  module Akeyless
    include AkeylessTargetSplunk
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
