# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_producer_k8s/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessProducerK8s
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_producer_k8s,
      attributes_class: Akeyless::Types::ProducerK8sAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:delete_protection, :k8s_allowed_namespaces, :k8s_cluster_ca_cert, :k8s_cluster_endpoint, :k8s_cluster_token, :k8s_namespace, :k8s_predefined_role_name, :k8s_predefined_role_type, :k8s_service_account, :k8s_service_account_type, :producer_encryption_key_name, :secure_access_bastion_issuer, :secure_access_cluster_endpoint, :secure_access_dashboard_url, :secure_access_enable, :tags, :target_name, :user_ttl],
      map_bool: [:secure_access_allow_port_forwading, :secure_access_web, :secure_access_web_browsing, :secure_access_web_proxy]
  end
  module Akeyless
    include AkeylessProducerK8s
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
