# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class GatewayLogForwardingElasticsearchAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute? :api_key, T::String.optional
    attribute? :auth_type, T::String.optional
    attribute? :cloud_id, T::String.optional
    attribute? :enable, T::String.optional
    attribute? :enable_tls, T::Bool.optional
    attribute? :index, T::String.optional
    attribute? :nodes, T::String.optional
    attribute? :output_format, T::String.optional
    attribute? :password, T::String.optional
    attribute? :pull_interval, T::String.optional
    attribute? :server_type, T::String.optional
    attribute? :tls_certificate, T::String.optional
    attribute? :user_name, T::String.optional
  end
end
