# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class GatewayLogForwardingLogstashAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute? :dns, T::String.optional
    attribute? :enable, T::String.optional
    attribute? :enable_tls, T::Bool.optional
    attribute? :output_format, T::String.optional
    attribute? :protocol, T::String.optional
    attribute? :pull_interval, T::String.optional
    attribute? :tls_certificate, T::String.optional
  end
end
