# Code generated by pangea-forge.
# InSpec profile for verifying akeyless_producer_cassandra infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AKEYLESS_TOKEN and AKEYLESS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/akeyless_producer_cassandra/ -t akeyless://

control 'akeyless_producer_cassandra-exists' do
  impact 1.0
  title 'Manages a akeyless_producer_cassandra resource'
  desc 'Verify that the akeyless_producer_cassandra resource exists and has expected properties'

  describe akeyless_producer_cassandra(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
  end
end
