# Code generated by pangea-forge.
# InSpec profile for verifying akeyless_dynamic_secret_redshift infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AKEYLESS_TOKEN and AKEYLESS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/akeyless_dynamic_secret_redshift/ -t akeyless://

control 'akeyless_dynamic_secret_redshift-exists' do
  impact 1.0
  title 'Manages a akeyless_dynamic_secret_redshift resource'
  desc 'Verify that the akeyless_dynamic_secret_redshift resource exists and has expected properties'

  describe akeyless_dynamic_secret_redshift(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
  end
end
