# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/akeyless_target_linked/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AkeylessTargetLinked
    include Pangea::Resources::ResourceBuilder

    define_resource :akeyless_target_linked,
      attributes_class: Akeyless::Types::TargetLinkedAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:description, :hosts, :parent_target_name, :type]
  end
  module Akeyless
    include AkeylessTargetLinked
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Akeyless)
