# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Akeyless::Types
  include Dry.Types()

  class RotatedSecretPostgresqlAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Akeyless::Types

    attribute :name, T::String
    attribute :rotator_type, T::String
    attribute :target_name, T::String
    attribute? :authentication_credentials, T::String.optional
    attribute? :auto_rotate, T::String.optional
    attribute? :description, T::String.optional
    attribute? :key, T::String.optional
    attribute? :password_length, T::String.optional
    attribute? :rotated_password, T::String.optional
    attribute? :rotated_username, T::String.optional
    attribute? :rotation_hour, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :rotation_interval, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
