# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_ssh_cert_issuer resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessSshCertIssuer do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { allowed_users: 'test-value', name: 'test-value', signer_key_name: 'test-value', ttl: 3.14 } }

  describe ':akeyless_ssh_cert_issuer' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'test')
        validate_required_attributes(config, [:allowed_users, :name, :signer_key_name, :ttl])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_ssh_cert_issuer('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_ssh_cert_issuer)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_ssh_cert_issuer('test', required_attrs)

        expect(ref.id).to eq("${akeyless_ssh_cert_issuer.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ delete_protection: true, description: 'test-value', extensions: { 'key1' => 'val1' }, principals: 'test-value', secure_access_bastion_api: 'test-value', secure_access_bastion_ssh: 'test-value', secure_access_enable: 'test-value', secure_access_host: ['test-value'], secure_access_ssh_creds_user: 'test-value', secure_access_use_internal_bastion: true, tags: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'full')
        expect(config).to have_key('delete_protection')
        expect(config).to have_key('description')
        expect(config).to have_key('extensions')
        expect(config).to have_key('principals')
        expect(config).to have_key('secure_access_bastion_api')
        expect(config).to have_key('secure_access_bastion_ssh')
        expect(config).to have_key('secure_access_enable')
        expect(config).to have_key('secure_access_host')
        expect(config).to have_key('secure_access_ssh_creds_user')
        expect(config).to have_key('secure_access_use_internal_bastion')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes delete_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('opt', required_attrs.merge(delete_protection: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'opt')
        expect(config).to have_key('delete_protection')
      end

      it 'omits delete_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'minimal')
        expect(config).not_to have_key('delete_protection')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes extensions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('opt', required_attrs.merge(extensions: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'opt')
        expect(config).to have_key('extensions')
      end

      it 'omits extensions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'minimal')
        expect(config).not_to have_key('extensions')
      end
      it 'includes principals when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('opt', required_attrs.merge(principals: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'opt')
        expect(config).to have_key('principals')
      end

      it 'omits principals when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'minimal')
        expect(config).not_to have_key('principals')
      end
      it 'includes secure_access_bastion_api when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('opt', required_attrs.merge(secure_access_bastion_api: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'opt')
        expect(config).to have_key('secure_access_bastion_api')
      end

      it 'omits secure_access_bastion_api when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'minimal')
        expect(config).not_to have_key('secure_access_bastion_api')
      end
      it 'includes secure_access_bastion_ssh when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('opt', required_attrs.merge(secure_access_bastion_ssh: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'opt')
        expect(config).to have_key('secure_access_bastion_ssh')
      end

      it 'omits secure_access_bastion_ssh when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'minimal')
        expect(config).not_to have_key('secure_access_bastion_ssh')
      end
      it 'includes secure_access_enable when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('opt', required_attrs.merge(secure_access_enable: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'opt')
        expect(config).to have_key('secure_access_enable')
      end

      it 'omits secure_access_enable when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'minimal')
        expect(config).not_to have_key('secure_access_enable')
      end
      it 'includes secure_access_host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('opt', required_attrs.merge(secure_access_host: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'opt')
        expect(config).to have_key('secure_access_host')
      end

      it 'omits secure_access_host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'minimal')
        expect(config).not_to have_key('secure_access_host')
      end
      it 'includes secure_access_ssh_creds_user when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('opt', required_attrs.merge(secure_access_ssh_creds_user: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'opt')
        expect(config).to have_key('secure_access_ssh_creds_user')
      end

      it 'omits secure_access_ssh_creds_user when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'minimal')
        expect(config).not_to have_key('secure_access_ssh_creds_user')
      end
      it 'includes secure_access_use_internal_bastion when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('opt', required_attrs.merge(secure_access_use_internal_bastion: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'opt')
        expect(config).to have_key('secure_access_use_internal_bastion')
      end

      it 'omits secure_access_use_internal_bastion when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'minimal')
        expect(config).not_to have_key('secure_access_use_internal_bastion')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts delete_protection=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(delete_protection: val)
          synth.akeyless_ssh_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', "bool_#{val}")
          expect(config['delete_protection']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts secure_access_use_internal_bastion=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(secure_access_use_internal_bastion: val)
          synth.akeyless_ssh_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', "bool_#{val}")
          expect(config['secure_access_use_internal_bastion']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_ssh_cert_issuer', 'typed')
        expect(config['allowed_users']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['signer_key_name']).to be_a(String)
        expect(config['ttl']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_ssh_cert_issuer('first', required_attrs)
        synth.akeyless_ssh_cert_issuer('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_ssh_cert_issuer')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_ssh_cert_issuer,
    method: :akeyless_ssh_cert_issuer,
    required_attrs: { allowed_users: 'test-value', name: 'test-value', signer_key_name: 'test-value', ttl: 3.14 },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:delete_protection, :secure_access_use_internal_bastion]
end
