# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_target_azure resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessTargetAzure do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':akeyless_target_azure' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_azure('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_target_azure', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_target_azure('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_target_azure)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_target_azure('test', required_attrs)

        expect(ref.id).to eq("${akeyless_target_azure.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ client_id: 'test-value', client_secret: 'test-value', description: 'test-value', key: 'test-value', tenant_id: 'test-value', use_gw_cloud_identity: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_azure('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_target_azure', 'full')
        expect(config).to have_key('client_id')
        expect(config).to have_key('client_secret')
        expect(config).to have_key('description')
        expect(config).to have_key('key')
        expect(config).to have_key('tenant_id')
        expect(config).to have_key('use_gw_cloud_identity')
      end
    end

    context 'optional attributes' do
      it 'includes client_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_azure('opt', required_attrs.merge(client_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_azure', 'opt')
        expect(config).to have_key('client_id')
      end

      it 'omits client_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_azure', 'minimal')
        expect(config).not_to have_key('client_id')
      end
      it 'includes client_secret when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_azure('opt', required_attrs.merge(client_secret: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_azure', 'opt')
        expect(config).to have_key('client_secret')
      end

      it 'omits client_secret when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_azure', 'minimal')
        expect(config).not_to have_key('client_secret')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_azure('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_azure', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_azure', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_azure('opt', required_attrs.merge(key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_azure', 'opt')
        expect(config).to have_key('key')
      end

      it 'omits key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_azure', 'minimal')
        expect(config).not_to have_key('key')
      end
      it 'includes tenant_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_azure('opt', required_attrs.merge(tenant_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_azure', 'opt')
        expect(config).to have_key('tenant_id')
      end

      it 'omits tenant_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_azure', 'minimal')
        expect(config).not_to have_key('tenant_id')
      end
      it 'includes use_gw_cloud_identity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_azure('opt', required_attrs.merge(use_gw_cloud_identity: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_azure', 'opt')
        expect(config).to have_key('use_gw_cloud_identity')
      end

      it 'omits use_gw_cloud_identity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_azure', 'minimal')
        expect(config).not_to have_key('use_gw_cloud_identity')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts use_gw_cloud_identity=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(use_gw_cloud_identity: val)
          synth.akeyless_target_azure("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_target_azure', "bool_#{val}")
          expect(config['use_gw_cloud_identity']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_azure('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_target_azure', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_azure('first', required_attrs)
        synth.akeyless_target_azure('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_target_azure')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_target_azure,
    method: :akeyless_target_azure,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:use_gw_cloud_identity]
end
