# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_gateway_cache resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessGatewayCache do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':akeyless_gateway_cache' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_gateway_cache('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_gateway_cache', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_gateway_cache('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_gateway_cache)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_gateway_cache('test', required_attrs)

        expect(ref.id).to eq("${akeyless_gateway_cache.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ backup_interval: 'test-value', enable_cache: 'test-value', enable_proactive: 'test-value', minimum_fetch_interval: 'test-value', stale_timeout: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_gateway_cache('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_gateway_cache', 'full')
        expect(config).to have_key('backup_interval')
        expect(config).to have_key('enable_cache')
        expect(config).to have_key('enable_proactive')
        expect(config).to have_key('minimum_fetch_interval')
        expect(config).to have_key('stale_timeout')
      end
    end

    context 'optional attributes' do
      it 'includes backup_interval when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_gateway_cache('opt', required_attrs.merge(backup_interval: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_gateway_cache', 'opt')
        expect(config).to have_key('backup_interval')
      end

      it 'omits backup_interval when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_gateway_cache('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_gateway_cache', 'minimal')
        expect(config).not_to have_key('backup_interval')
      end
      it 'includes enable_cache when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_gateway_cache('opt', required_attrs.merge(enable_cache: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_gateway_cache', 'opt')
        expect(config).to have_key('enable_cache')
      end

      it 'omits enable_cache when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_gateway_cache('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_gateway_cache', 'minimal')
        expect(config).not_to have_key('enable_cache')
      end
      it 'includes enable_proactive when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_gateway_cache('opt', required_attrs.merge(enable_proactive: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_gateway_cache', 'opt')
        expect(config).to have_key('enable_proactive')
      end

      it 'omits enable_proactive when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_gateway_cache('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_gateway_cache', 'minimal')
        expect(config).not_to have_key('enable_proactive')
      end
      it 'includes minimum_fetch_interval when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_gateway_cache('opt', required_attrs.merge(minimum_fetch_interval: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_gateway_cache', 'opt')
        expect(config).to have_key('minimum_fetch_interval')
      end

      it 'omits minimum_fetch_interval when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_gateway_cache('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_gateway_cache', 'minimal')
        expect(config).not_to have_key('minimum_fetch_interval')
      end
      it 'includes stale_timeout when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_gateway_cache('opt', required_attrs.merge(stale_timeout: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_gateway_cache', 'opt')
        expect(config).to have_key('stale_timeout')
      end

      it 'omits stale_timeout when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_gateway_cache('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_gateway_cache', 'minimal')
        expect(config).not_to have_key('stale_timeout')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_gateway_cache('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_gateway_cache', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_gateway_cache('first', required_attrs)
        synth.akeyless_gateway_cache('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_gateway_cache')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_gateway_cache,
    method: :akeyless_gateway_cache,
    required_attrs: {},
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
