# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_producer_custom resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessProducerCustom do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { create_sync_url: 'test-value', name: 'test-value', revoke_sync_url: 'test-value' } }

  describe ':akeyless_producer_custom' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'test')
        validate_required_attributes(config, [:create_sync_url, :name, :revoke_sync_url])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_producer_custom('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_producer_custom)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_producer_custom('test', required_attrs)

        expect(ref.id).to eq("${akeyless_producer_custom.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ admin_rotation_interval_days: 3.14, enable_admin_rotation: true, payload: 'test-value', producer_encryption_key_name: 'test-value', rotate_sync_url: 'test-value', tags: ['test-value'], timeout_sec: 3.14, user_ttl: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_producer_custom', 'full')
        expect(config).to have_key('admin_rotation_interval_days')
        expect(config).to have_key('enable_admin_rotation')
        expect(config).to have_key('payload')
        expect(config).to have_key('producer_encryption_key_name')
        expect(config).to have_key('rotate_sync_url')
        expect(config).to have_key('tags')
        expect(config).to have_key('timeout_sec')
        expect(config).to have_key('user_ttl')
      end
    end

    context 'optional attributes' do
      it 'includes admin_rotation_interval_days when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('opt', required_attrs.merge(admin_rotation_interval_days: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'opt')
        expect(config).to have_key('admin_rotation_interval_days')
      end

      it 'omits admin_rotation_interval_days when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'minimal')
        expect(config).not_to have_key('admin_rotation_interval_days')
      end
      it 'includes enable_admin_rotation when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('opt', required_attrs.merge(enable_admin_rotation: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'opt')
        expect(config).to have_key('enable_admin_rotation')
      end

      it 'omits enable_admin_rotation when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'minimal')
        expect(config).not_to have_key('enable_admin_rotation')
      end
      it 'includes payload when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('opt', required_attrs.merge(payload: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'opt')
        expect(config).to have_key('payload')
      end

      it 'omits payload when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'minimal')
        expect(config).not_to have_key('payload')
      end
      it 'includes producer_encryption_key_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('opt', required_attrs.merge(producer_encryption_key_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'opt')
        expect(config).to have_key('producer_encryption_key_name')
      end

      it 'omits producer_encryption_key_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'minimal')
        expect(config).not_to have_key('producer_encryption_key_name')
      end
      it 'includes rotate_sync_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('opt', required_attrs.merge(rotate_sync_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'opt')
        expect(config).to have_key('rotate_sync_url')
      end

      it 'omits rotate_sync_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'minimal')
        expect(config).not_to have_key('rotate_sync_url')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes timeout_sec when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('opt', required_attrs.merge(timeout_sec: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'opt')
        expect(config).to have_key('timeout_sec')
      end

      it 'omits timeout_sec when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'minimal')
        expect(config).not_to have_key('timeout_sec')
      end
      it 'includes user_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('opt', required_attrs.merge(user_ttl: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'opt')
        expect(config).to have_key('user_ttl')
      end

      it 'omits user_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_custom', 'minimal')
        expect(config).not_to have_key('user_ttl')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enable_admin_rotation=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_admin_rotation: val)
          synth.akeyless_producer_custom("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_producer_custom', "bool_#{val}")
          expect(config['enable_admin_rotation']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_producer_custom', 'typed')
        expect(config['create_sync_url']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['revoke_sync_url']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_custom('first', required_attrs)
        synth.akeyless_producer_custom('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_producer_custom')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_producer_custom,
    method: :akeyless_producer_custom,
    required_attrs: { create_sync_url: 'test-value', name: 'test-value', revoke_sync_url: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enable_admin_rotation]
end
