# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_producer_oracle resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessProducerOracle do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':akeyless_producer_oracle' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_producer_oracle('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_producer_oracle)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_producer_oracle('test', required_attrs)

        expect(ref.id).to eq("${akeyless_producer_oracle.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ db_server_certificates: 'test-value', db_server_name: 'test-value', oracle_host: 'test-value', oracle_password: 'test-value', oracle_port: 'test-value', oracle_screation_statements: 'test-value', oracle_service_name: 'test-value', oracle_username: 'test-value', producer_encryption_key_name: 'test-value', tags: ['test-value'], target_name: 'test-value', user_ttl: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'full')
        expect(config).to have_key('db_server_certificates')
        expect(config).to have_key('db_server_name')
        expect(config).to have_key('oracle_host')
        expect(config).to have_key('oracle_password')
        expect(config).to have_key('oracle_port')
        expect(config).to have_key('oracle_screation_statements')
        expect(config).to have_key('oracle_service_name')
        expect(config).to have_key('oracle_username')
        expect(config).to have_key('producer_encryption_key_name')
        expect(config).to have_key('tags')
        expect(config).to have_key('target_name')
        expect(config).to have_key('user_ttl')
      end
    end

    context 'optional attributes' do
      it 'includes db_server_certificates when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('opt', required_attrs.merge(db_server_certificates: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'opt')
        expect(config).to have_key('db_server_certificates')
      end

      it 'omits db_server_certificates when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'minimal')
        expect(config).not_to have_key('db_server_certificates')
      end
      it 'includes db_server_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('opt', required_attrs.merge(db_server_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'opt')
        expect(config).to have_key('db_server_name')
      end

      it 'omits db_server_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'minimal')
        expect(config).not_to have_key('db_server_name')
      end
      it 'includes oracle_host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('opt', required_attrs.merge(oracle_host: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'opt')
        expect(config).to have_key('oracle_host')
      end

      it 'omits oracle_host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'minimal')
        expect(config).not_to have_key('oracle_host')
      end
      it 'includes oracle_password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('opt', required_attrs.merge(oracle_password: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'opt')
        expect(config).to have_key('oracle_password')
      end

      it 'omits oracle_password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'minimal')
        expect(config).not_to have_key('oracle_password')
      end
      it 'includes oracle_port when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('opt', required_attrs.merge(oracle_port: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'opt')
        expect(config).to have_key('oracle_port')
      end

      it 'omits oracle_port when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'minimal')
        expect(config).not_to have_key('oracle_port')
      end
      it 'includes oracle_screation_statements when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('opt', required_attrs.merge(oracle_screation_statements: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'opt')
        expect(config).to have_key('oracle_screation_statements')
      end

      it 'omits oracle_screation_statements when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'minimal')
        expect(config).not_to have_key('oracle_screation_statements')
      end
      it 'includes oracle_service_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('opt', required_attrs.merge(oracle_service_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'opt')
        expect(config).to have_key('oracle_service_name')
      end

      it 'omits oracle_service_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'minimal')
        expect(config).not_to have_key('oracle_service_name')
      end
      it 'includes oracle_username when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('opt', required_attrs.merge(oracle_username: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'opt')
        expect(config).to have_key('oracle_username')
      end

      it 'omits oracle_username when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'minimal')
        expect(config).not_to have_key('oracle_username')
      end
      it 'includes producer_encryption_key_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('opt', required_attrs.merge(producer_encryption_key_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'opt')
        expect(config).to have_key('producer_encryption_key_name')
      end

      it 'omits producer_encryption_key_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'minimal')
        expect(config).not_to have_key('producer_encryption_key_name')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes target_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('opt', required_attrs.merge(target_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'opt')
        expect(config).to have_key('target_name')
      end

      it 'omits target_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'minimal')
        expect(config).not_to have_key('target_name')
      end
      it 'includes user_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('opt', required_attrs.merge(user_ttl: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'opt')
        expect(config).to have_key('user_ttl')
      end

      it 'omits user_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'minimal')
        expect(config).not_to have_key('user_ttl')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_producer_oracle', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_oracle('first', required_attrs)
        synth.akeyless_producer_oracle('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_producer_oracle')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_producer_oracle,
    method: :akeyless_producer_oracle,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
