# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':akeyless_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_role', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_role('test', required_attrs)

        expect(ref.id).to eq("${akeyless_role.test.id}")
        expect(ref.restricted_rules).to eq("${akeyless_role.test.restricted_rules}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_role', 'test')
        expect(config).not_to have_key('restricted_rules')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ analytics_access: 'test-value', assoc_auth_method: [{ 'key1' => 'val1' }], audit_access: 'test-value', delete_protection: 'test-value', description: 'test-value', event_center_access: 'test-value', event_forwarders_access: 'test-value', gw_analytics_access: 'test-value', rules: [{ 'key1' => 'val1' }], sra_reports_access: 'test-value', usage_reports_access: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_role', 'full')
        expect(config).to have_key('analytics_access')
        expect(config).to have_key('assoc_auth_method')
        expect(config).to have_key('audit_access')
        expect(config).to have_key('delete_protection')
        expect(config).to have_key('description')
        expect(config).to have_key('event_center_access')
        expect(config).to have_key('event_forwarders_access')
        expect(config).to have_key('gw_analytics_access')
        expect(config).to have_key('rules')
        expect(config).to have_key('sra_reports_access')
        expect(config).to have_key('usage_reports_access')
      end
    end

    context 'optional attributes' do
      it 'includes analytics_access when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('opt', required_attrs.merge(analytics_access: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'opt')
        expect(config).to have_key('analytics_access')
      end

      it 'omits analytics_access when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'minimal')
        expect(config).not_to have_key('analytics_access')
      end
      it 'includes assoc_auth_method when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('opt', required_attrs.merge(assoc_auth_method: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'opt')
        expect(config).to have_key('assoc_auth_method')
      end

      it 'omits assoc_auth_method when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'minimal')
        expect(config).not_to have_key('assoc_auth_method')
      end
      it 'includes audit_access when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('opt', required_attrs.merge(audit_access: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'opt')
        expect(config).to have_key('audit_access')
      end

      it 'omits audit_access when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'minimal')
        expect(config).not_to have_key('audit_access')
      end
      it 'includes delete_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('opt', required_attrs.merge(delete_protection: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'opt')
        expect(config).to have_key('delete_protection')
      end

      it 'omits delete_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'minimal')
        expect(config).not_to have_key('delete_protection')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes event_center_access when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('opt', required_attrs.merge(event_center_access: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'opt')
        expect(config).to have_key('event_center_access')
      end

      it 'omits event_center_access when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'minimal')
        expect(config).not_to have_key('event_center_access')
      end
      it 'includes event_forwarders_access when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('opt', required_attrs.merge(event_forwarders_access: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'opt')
        expect(config).to have_key('event_forwarders_access')
      end

      it 'omits event_forwarders_access when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'minimal')
        expect(config).not_to have_key('event_forwarders_access')
      end
      it 'includes gw_analytics_access when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('opt', required_attrs.merge(gw_analytics_access: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'opt')
        expect(config).to have_key('gw_analytics_access')
      end

      it 'omits gw_analytics_access when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'minimal')
        expect(config).not_to have_key('gw_analytics_access')
      end
      it 'includes rules when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('opt', required_attrs.merge(rules: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'opt')
        expect(config).to have_key('rules')
      end

      it 'omits rules when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'minimal')
        expect(config).not_to have_key('rules')
      end
      it 'includes sra_reports_access when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('opt', required_attrs.merge(sra_reports_access: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'opt')
        expect(config).to have_key('sra_reports_access')
      end

      it 'omits sra_reports_access when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'minimal')
        expect(config).not_to have_key('sra_reports_access')
      end
      it 'includes usage_reports_access when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('opt', required_attrs.merge(usage_reports_access: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'opt')
        expect(config).to have_key('usage_reports_access')
      end

      it 'omits usage_reports_access when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_role', 'minimal')
        expect(config).not_to have_key('usage_reports_access')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_role', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_role('first', required_attrs)
        synth.akeyless_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_role,
    method: :akeyless_role,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :restricted_rules],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
