# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_auth_method_ldap resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessAuthMethodLdap do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':akeyless_auth_method_ldap' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_auth_method_ldap('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_auth_method_ldap)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_auth_method_ldap('test', required_attrs)

        expect(ref.id).to eq("${akeyless_auth_method_ldap.test.id}")
        expect(ref.access_id).to eq("${akeyless_auth_method_ldap.test.access_id}")
        expect(ref.private_key_data).to eq("${akeyless_auth_method_ldap.test.private_key_data}")
        expect(ref.public_key_data).to eq("${akeyless_auth_method_ldap.test.public_key_data}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'test')
        expect(config).not_to have_key('access_id')
        expect(config).not_to have_key('private_key_data')
        expect(config).not_to have_key('public_key_data')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ access_expires: 3.14, audit_logs_claims: ['test-value'], bound_ips: ['test-value'], delete_protection: 'test-value', description: 'test-value', expiration_event_in: ['test-value'], force_sub_claims: true, gen_key: 'test-value', gw_bound_ips: ['test-value'], jwt_ttl: 3.14, product_type: ['test-value'], public_key_data: 'test-value', unique_identifier: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'full')
        expect(config).to have_key('access_expires')
        expect(config).to have_key('audit_logs_claims')
        expect(config).to have_key('bound_ips')
        expect(config).to have_key('delete_protection')
        expect(config).to have_key('description')
        expect(config).to have_key('expiration_event_in')
        expect(config).to have_key('force_sub_claims')
        expect(config).to have_key('gen_key')
        expect(config).to have_key('gw_bound_ips')
        expect(config).to have_key('jwt_ttl')
        expect(config).to have_key('product_type')
        expect(config).to have_key('public_key_data')
        expect(config).to have_key('unique_identifier')
      end
    end

    context 'optional attributes' do
      it 'includes access_expires when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('opt', required_attrs.merge(access_expires: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'opt')
        expect(config).to have_key('access_expires')
      end

      it 'omits access_expires when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'minimal')
        expect(config).not_to have_key('access_expires')
      end
      it 'includes audit_logs_claims when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('opt', required_attrs.merge(audit_logs_claims: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'opt')
        expect(config).to have_key('audit_logs_claims')
      end

      it 'omits audit_logs_claims when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'minimal')
        expect(config).not_to have_key('audit_logs_claims')
      end
      it 'includes bound_ips when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('opt', required_attrs.merge(bound_ips: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'opt')
        expect(config).to have_key('bound_ips')
      end

      it 'omits bound_ips when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'minimal')
        expect(config).not_to have_key('bound_ips')
      end
      it 'includes delete_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('opt', required_attrs.merge(delete_protection: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'opt')
        expect(config).to have_key('delete_protection')
      end

      it 'omits delete_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'minimal')
        expect(config).not_to have_key('delete_protection')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes expiration_event_in when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('opt', required_attrs.merge(expiration_event_in: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'opt')
        expect(config).to have_key('expiration_event_in')
      end

      it 'omits expiration_event_in when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'minimal')
        expect(config).not_to have_key('expiration_event_in')
      end
      it 'includes force_sub_claims when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('opt', required_attrs.merge(force_sub_claims: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'opt')
        expect(config).to have_key('force_sub_claims')
      end

      it 'omits force_sub_claims when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'minimal')
        expect(config).not_to have_key('force_sub_claims')
      end
      it 'includes gen_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('opt', required_attrs.merge(gen_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'opt')
        expect(config).to have_key('gen_key')
      end

      it 'omits gen_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'minimal')
        expect(config).not_to have_key('gen_key')
      end
      it 'includes gw_bound_ips when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('opt', required_attrs.merge(gw_bound_ips: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'opt')
        expect(config).to have_key('gw_bound_ips')
      end

      it 'omits gw_bound_ips when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'minimal')
        expect(config).not_to have_key('gw_bound_ips')
      end
      it 'includes jwt_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('opt', required_attrs.merge(jwt_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'opt')
        expect(config).to have_key('jwt_ttl')
      end

      it 'omits jwt_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'minimal')
        expect(config).not_to have_key('jwt_ttl')
      end
      it 'includes product_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('opt', required_attrs.merge(product_type: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'opt')
        expect(config).to have_key('product_type')
      end

      it 'omits product_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'minimal')
        expect(config).not_to have_key('product_type')
      end
      it 'includes public_key_data when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('opt', required_attrs.merge(public_key_data: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'opt')
        expect(config).to have_key('public_key_data')
      end

      it 'omits public_key_data when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'minimal')
        expect(config).not_to have_key('public_key_data')
      end
      it 'includes unique_identifier when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('opt', required_attrs.merge(unique_identifier: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'opt')
        expect(config).to have_key('unique_identifier')
      end

      it 'omits unique_identifier when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'minimal')
        expect(config).not_to have_key('unique_identifier')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:private_key_data]
        expect(sensitive_fields).to include(:private_key_data)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts force_sub_claims=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(force_sub_claims: val)
          synth.akeyless_auth_method_ldap("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_auth_method_ldap', "bool_#{val}")
          expect(config['force_sub_claims']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_auth_method_ldap', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_ldap('first', required_attrs)
        synth.akeyless_auth_method_ldap('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_auth_method_ldap')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_auth_method_ldap,
    method: :akeyless_auth_method_ldap,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :access_id, :private_key_data, :public_key_data],
    sensitive_fields: [:private_key_data],
    immutable_fields: [],
    boolean_fields: [:force_sub_claims]
end
