# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_target_zerossl resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessTargetZerossl do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { api_key: 'test-value', imap_fqdn: 'test-value', imap_password: 'test-value', imap_username: 'test-value', name: 'test-value' } }

  describe ':akeyless_target_zerossl' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_zerossl('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_target_zerossl', 'test')
        validate_required_attributes(config, [:api_key, :imap_fqdn, :imap_password, :imap_username, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_target_zerossl('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_target_zerossl)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_target_zerossl('test', required_attrs)

        expect(ref.id).to eq("${akeyless_target_zerossl.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', imap_port: 'test-value', imap_target_email: 'test-value', key: 'test-value', timeout: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_zerossl('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_target_zerossl', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('imap_port')
        expect(config).to have_key('imap_target_email')
        expect(config).to have_key('key')
        expect(config).to have_key('timeout')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_zerossl('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_zerossl', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_zerossl('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_zerossl', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes imap_port when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_zerossl('opt', required_attrs.merge(imap_port: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_zerossl', 'opt')
        expect(config).to have_key('imap_port')
      end

      it 'omits imap_port when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_zerossl('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_zerossl', 'minimal')
        expect(config).not_to have_key('imap_port')
      end
      it 'includes imap_target_email when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_zerossl('opt', required_attrs.merge(imap_target_email: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_zerossl', 'opt')
        expect(config).to have_key('imap_target_email')
      end

      it 'omits imap_target_email when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_zerossl('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_zerossl', 'minimal')
        expect(config).not_to have_key('imap_target_email')
      end
      it 'includes key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_zerossl('opt', required_attrs.merge(key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_zerossl', 'opt')
        expect(config).to have_key('key')
      end

      it 'omits key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_zerossl('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_zerossl', 'minimal')
        expect(config).not_to have_key('key')
      end
      it 'includes timeout when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_zerossl('opt', required_attrs.merge(timeout: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_zerossl', 'opt')
        expect(config).to have_key('timeout')
      end

      it 'omits timeout when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_zerossl('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_zerossl', 'minimal')
        expect(config).not_to have_key('timeout')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:api_key, :imap_password]
        expect(sensitive_fields).to include(:api_key)
        expect(sensitive_fields).to include(:imap_password)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_zerossl('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_target_zerossl', 'typed')
        expect(config['api_key']).to be_a(String)
        expect(config['imap_fqdn']).to be_a(String)
        expect(config['imap_password']).to be_a(String)
        expect(config['imap_username']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_zerossl('first', required_attrs)
        synth.akeyless_target_zerossl('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_target_zerossl')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_target_zerossl,
    method: :akeyless_target_zerossl,
    required_attrs: { api_key: 'test-value', imap_fqdn: 'test-value', imap_password: 'test-value', imap_username: 'test-value', name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [:api_key, :imap_password],
    immutable_fields: [],
    boolean_fields: []
end
