# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_rotated_secret_gcp resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessRotatedSecretGcp do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', rotator_type: 'test-value', target_name: 'test-value' } }

  describe ':akeyless_rotated_secret_gcp' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'test')
        validate_required_attributes(config, [:name, :rotator_type, :target_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_rotated_secret_gcp('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_rotated_secret_gcp)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_rotated_secret_gcp('test', required_attrs)

        expect(ref.id).to eq("${akeyless_rotated_secret_gcp.test.id}")
        expect(ref.gcp_key).to eq("${akeyless_rotated_secret_gcp.test.gcp_key}")
        expect(ref.key).to eq("${akeyless_rotated_secret_gcp.test.key}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'test')
        expect(config).not_to have_key('gcp_key')
        expect(config).not_to have_key('key')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ authentication_credentials: 'test-value', auto_rotate: 'test-value', description: 'test-value', gcp_key: 'test-value', gcp_service_account_email: 'test-value', gcp_service_account_key_id: 'test-value', key: 'test-value', password_length: 'test-value', rotation_hour: 3.14, rotation_interval: 'test-value', tags: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'full')
        expect(config).to have_key('authentication_credentials')
        expect(config).to have_key('auto_rotate')
        expect(config).to have_key('description')
        expect(config).to have_key('gcp_key')
        expect(config).to have_key('gcp_service_account_email')
        expect(config).to have_key('gcp_service_account_key_id')
        expect(config).to have_key('key')
        expect(config).to have_key('password_length')
        expect(config).to have_key('rotation_hour')
        expect(config).to have_key('rotation_interval')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes authentication_credentials when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('opt', required_attrs.merge(authentication_credentials: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'opt')
        expect(config).to have_key('authentication_credentials')
      end

      it 'omits authentication_credentials when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'minimal')
        expect(config).not_to have_key('authentication_credentials')
      end
      it 'includes auto_rotate when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('opt', required_attrs.merge(auto_rotate: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'opt')
        expect(config).to have_key('auto_rotate')
      end

      it 'omits auto_rotate when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'minimal')
        expect(config).not_to have_key('auto_rotate')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes gcp_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('opt', required_attrs.merge(gcp_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'opt')
        expect(config).to have_key('gcp_key')
      end

      it 'omits gcp_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'minimal')
        expect(config).not_to have_key('gcp_key')
      end
      it 'includes gcp_service_account_email when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('opt', required_attrs.merge(gcp_service_account_email: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'opt')
        expect(config).to have_key('gcp_service_account_email')
      end

      it 'omits gcp_service_account_email when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'minimal')
        expect(config).not_to have_key('gcp_service_account_email')
      end
      it 'includes gcp_service_account_key_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('opt', required_attrs.merge(gcp_service_account_key_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'opt')
        expect(config).to have_key('gcp_service_account_key_id')
      end

      it 'omits gcp_service_account_key_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'minimal')
        expect(config).not_to have_key('gcp_service_account_key_id')
      end
      it 'includes key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('opt', required_attrs.merge(key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'opt')
        expect(config).to have_key('key')
      end

      it 'omits key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'minimal')
        expect(config).not_to have_key('key')
      end
      it 'includes password_length when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('opt', required_attrs.merge(password_length: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'opt')
        expect(config).to have_key('password_length')
      end

      it 'omits password_length when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'minimal')
        expect(config).not_to have_key('password_length')
      end
      it 'includes rotation_hour when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('opt', required_attrs.merge(rotation_hour: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'opt')
        expect(config).to have_key('rotation_hour')
      end

      it 'omits rotation_hour when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'minimal')
        expect(config).not_to have_key('rotation_hour')
      end
      it 'includes rotation_interval when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('opt', required_attrs.merge(rotation_interval: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'opt')
        expect(config).to have_key('rotation_interval')
      end

      it 'omits rotation_interval when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'minimal')
        expect(config).not_to have_key('rotation_interval')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_rotated_secret_gcp', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['rotator_type']).to be_a(String)
        expect(config['target_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_gcp('first', required_attrs)
        synth.akeyless_rotated_secret_gcp('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_rotated_secret_gcp')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_rotated_secret_gcp,
    method: :akeyless_rotated_secret_gcp,
    required_attrs: { name: 'test-value', rotator_type: 'test-value', target_name: 'test-value' },
    expected_outputs: [:id, :gcp_key, :key],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
