# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_pki_cert_issuer resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessPkiCertIssuer do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', ttl: 'test-value' } }

  describe ':akeyless_pki_cert_issuer' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'test')
        validate_required_attributes(config, [:name, :ttl])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_pki_cert_issuer('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_pki_cert_issuer)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_pki_cert_issuer('test', required_attrs)

        expect(ref.id).to eq("${akeyless_pki_cert_issuer.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allow_any_name: true, allow_copy_ext_from_csr: true, allow_subdomains: true, allowed_domains: 'test-value', allowed_extra_extensions: 'test-value', allowed_ip_sans: 'test-value', allowed_uri_sans: 'test-value', auto_renew: true, ca_target: 'test-value', client_flag: true, code_signing_flag: true, country: 'test-value', create_private_crl: true, create_public_crl: true, critical_key_usage: 'test-value', delete_protection: true, description: 'test-value', destination_path: 'test-value', enable_acme: true, expiration_event_in: ['test-value'], gw_cluster_url: 'test-value', is_ca: true, key_usage: 'test-value', locality: 'test-value', not_enforce_hostnames: true, not_require_cn: true, organizational_units: 'test-value', organizations: 'test-value', postal_code: 'test-value', protect_certificates: true, province: 'test-value', scheduled_renew: 3.14, server_flag: true, signer_key_name: 'test-value', street_address: 'test-value', tags: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'full')
        expect(config).to have_key('allow_any_name')
        expect(config).to have_key('allow_copy_ext_from_csr')
        expect(config).to have_key('allow_subdomains')
        expect(config).to have_key('allowed_domains')
        expect(config).to have_key('allowed_extra_extensions')
        expect(config).to have_key('allowed_ip_sans')
        expect(config).to have_key('allowed_uri_sans')
        expect(config).to have_key('auto_renew')
        expect(config).to have_key('ca_target')
        expect(config).to have_key('client_flag')
        expect(config).to have_key('code_signing_flag')
        expect(config).to have_key('country')
        expect(config).to have_key('create_private_crl')
        expect(config).to have_key('create_public_crl')
        expect(config).to have_key('critical_key_usage')
        expect(config).to have_key('delete_protection')
        expect(config).to have_key('description')
        expect(config).to have_key('destination_path')
        expect(config).to have_key('enable_acme')
        expect(config).to have_key('expiration_event_in')
        expect(config).to have_key('gw_cluster_url')
        expect(config).to have_key('is_ca')
        expect(config).to have_key('key_usage')
        expect(config).to have_key('locality')
        expect(config).to have_key('not_enforce_hostnames')
        expect(config).to have_key('not_require_cn')
        expect(config).to have_key('organizational_units')
        expect(config).to have_key('organizations')
        expect(config).to have_key('postal_code')
        expect(config).to have_key('protect_certificates')
        expect(config).to have_key('province')
        expect(config).to have_key('scheduled_renew')
        expect(config).to have_key('server_flag')
        expect(config).to have_key('signer_key_name')
        expect(config).to have_key('street_address')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes allow_any_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(allow_any_name: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('allow_any_name')
      end

      it 'omits allow_any_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('allow_any_name')
      end
      it 'includes allow_copy_ext_from_csr when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(allow_copy_ext_from_csr: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('allow_copy_ext_from_csr')
      end

      it 'omits allow_copy_ext_from_csr when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('allow_copy_ext_from_csr')
      end
      it 'includes allow_subdomains when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(allow_subdomains: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('allow_subdomains')
      end

      it 'omits allow_subdomains when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('allow_subdomains')
      end
      it 'includes allowed_domains when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(allowed_domains: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('allowed_domains')
      end

      it 'omits allowed_domains when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('allowed_domains')
      end
      it 'includes allowed_extra_extensions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(allowed_extra_extensions: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('allowed_extra_extensions')
      end

      it 'omits allowed_extra_extensions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('allowed_extra_extensions')
      end
      it 'includes allowed_ip_sans when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(allowed_ip_sans: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('allowed_ip_sans')
      end

      it 'omits allowed_ip_sans when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('allowed_ip_sans')
      end
      it 'includes allowed_uri_sans when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(allowed_uri_sans: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('allowed_uri_sans')
      end

      it 'omits allowed_uri_sans when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('allowed_uri_sans')
      end
      it 'includes auto_renew when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(auto_renew: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('auto_renew')
      end

      it 'omits auto_renew when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('auto_renew')
      end
      it 'includes ca_target when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(ca_target: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('ca_target')
      end

      it 'omits ca_target when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('ca_target')
      end
      it 'includes client_flag when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(client_flag: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('client_flag')
      end

      it 'omits client_flag when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('client_flag')
      end
      it 'includes code_signing_flag when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(code_signing_flag: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('code_signing_flag')
      end

      it 'omits code_signing_flag when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('code_signing_flag')
      end
      it 'includes country when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(country: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('country')
      end

      it 'omits country when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('country')
      end
      it 'includes create_private_crl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(create_private_crl: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('create_private_crl')
      end

      it 'omits create_private_crl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('create_private_crl')
      end
      it 'includes create_public_crl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(create_public_crl: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('create_public_crl')
      end

      it 'omits create_public_crl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('create_public_crl')
      end
      it 'includes critical_key_usage when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(critical_key_usage: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('critical_key_usage')
      end

      it 'omits critical_key_usage when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('critical_key_usage')
      end
      it 'includes delete_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(delete_protection: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('delete_protection')
      end

      it 'omits delete_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('delete_protection')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes destination_path when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(destination_path: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('destination_path')
      end

      it 'omits destination_path when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('destination_path')
      end
      it 'includes enable_acme when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(enable_acme: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('enable_acme')
      end

      it 'omits enable_acme when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('enable_acme')
      end
      it 'includes expiration_event_in when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(expiration_event_in: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('expiration_event_in')
      end

      it 'omits expiration_event_in when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('expiration_event_in')
      end
      it 'includes gw_cluster_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(gw_cluster_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('gw_cluster_url')
      end

      it 'omits gw_cluster_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('gw_cluster_url')
      end
      it 'includes is_ca when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(is_ca: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('is_ca')
      end

      it 'omits is_ca when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('is_ca')
      end
      it 'includes key_usage when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(key_usage: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('key_usage')
      end

      it 'omits key_usage when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('key_usage')
      end
      it 'includes locality when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(locality: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('locality')
      end

      it 'omits locality when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('locality')
      end
      it 'includes not_enforce_hostnames when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(not_enforce_hostnames: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('not_enforce_hostnames')
      end

      it 'omits not_enforce_hostnames when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('not_enforce_hostnames')
      end
      it 'includes not_require_cn when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(not_require_cn: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('not_require_cn')
      end

      it 'omits not_require_cn when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('not_require_cn')
      end
      it 'includes organizational_units when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(organizational_units: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('organizational_units')
      end

      it 'omits organizational_units when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('organizational_units')
      end
      it 'includes organizations when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(organizations: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('organizations')
      end

      it 'omits organizations when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('organizations')
      end
      it 'includes postal_code when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(postal_code: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('postal_code')
      end

      it 'omits postal_code when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('postal_code')
      end
      it 'includes protect_certificates when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(protect_certificates: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('protect_certificates')
      end

      it 'omits protect_certificates when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('protect_certificates')
      end
      it 'includes province when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(province: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('province')
      end

      it 'omits province when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('province')
      end
      it 'includes scheduled_renew when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(scheduled_renew: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('scheduled_renew')
      end

      it 'omits scheduled_renew when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('scheduled_renew')
      end
      it 'includes server_flag when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(server_flag: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('server_flag')
      end

      it 'omits server_flag when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('server_flag')
      end
      it 'includes signer_key_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(signer_key_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('signer_key_name')
      end

      it 'omits signer_key_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('signer_key_name')
      end
      it 'includes street_address when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(street_address: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('street_address')
      end

      it 'omits street_address when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('street_address')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts allow_any_name=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_any_name: val)
          synth.akeyless_pki_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', "bool_#{val}")
          expect(config['allow_any_name']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts allow_copy_ext_from_csr=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_copy_ext_from_csr: val)
          synth.akeyless_pki_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', "bool_#{val}")
          expect(config['allow_copy_ext_from_csr']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts allow_subdomains=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_subdomains: val)
          synth.akeyless_pki_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', "bool_#{val}")
          expect(config['allow_subdomains']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts auto_renew=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(auto_renew: val)
          synth.akeyless_pki_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', "bool_#{val}")
          expect(config['auto_renew']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts client_flag=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(client_flag: val)
          synth.akeyless_pki_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', "bool_#{val}")
          expect(config['client_flag']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts code_signing_flag=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(code_signing_flag: val)
          synth.akeyless_pki_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', "bool_#{val}")
          expect(config['code_signing_flag']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts create_private_crl=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(create_private_crl: val)
          synth.akeyless_pki_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', "bool_#{val}")
          expect(config['create_private_crl']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts create_public_crl=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(create_public_crl: val)
          synth.akeyless_pki_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', "bool_#{val}")
          expect(config['create_public_crl']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts delete_protection=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(delete_protection: val)
          synth.akeyless_pki_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', "bool_#{val}")
          expect(config['delete_protection']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enable_acme=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_acme: val)
          synth.akeyless_pki_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', "bool_#{val}")
          expect(config['enable_acme']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts is_ca=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_ca: val)
          synth.akeyless_pki_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', "bool_#{val}")
          expect(config['is_ca']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts not_enforce_hostnames=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(not_enforce_hostnames: val)
          synth.akeyless_pki_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', "bool_#{val}")
          expect(config['not_enforce_hostnames']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts not_require_cn=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(not_require_cn: val)
          synth.akeyless_pki_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', "bool_#{val}")
          expect(config['not_require_cn']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts protect_certificates=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(protect_certificates: val)
          synth.akeyless_pki_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', "bool_#{val}")
          expect(config['protect_certificates']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts server_flag=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(server_flag: val)
          synth.akeyless_pki_cert_issuer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', "bool_#{val}")
          expect(config['server_flag']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_pki_cert_issuer', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['ttl']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_pki_cert_issuer('first', required_attrs)
        synth.akeyless_pki_cert_issuer('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_pki_cert_issuer')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_pki_cert_issuer,
    method: :akeyless_pki_cert_issuer,
    required_attrs: { name: 'test-value', ttl: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:allow_any_name, :allow_copy_ext_from_csr, :allow_subdomains, :auto_renew, :client_flag, :code_signing_flag, :create_private_crl, :create_public_crl, :delete_protection, :enable_acme, :is_ca, :not_enforce_hostnames, :not_require_cn, :protect_certificates, :server_flag]
end
