# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_rotated_secret_sync resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessRotatedSecretSync do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', remote_secret_name: 'test-value', usc_name: 'test-value' } }

  describe ':akeyless_rotated_secret_sync' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_sync('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_sync', 'test')
        validate_required_attributes(config, [:name, :remote_secret_name, :usc_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_rotated_secret_sync('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_rotated_secret_sync)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_rotated_secret_sync('test', required_attrs)

        expect(ref.id).to eq("${akeyless_rotated_secret_sync.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ filter_secret_value: 'test-value', namespace: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_sync('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_rotated_secret_sync', 'full')
        expect(config).to have_key('filter_secret_value')
        expect(config).to have_key('namespace')
      end
    end

    context 'optional attributes' do
      it 'includes filter_secret_value when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_sync('opt', required_attrs.merge(filter_secret_value: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_sync', 'opt')
        expect(config).to have_key('filter_secret_value')
      end

      it 'omits filter_secret_value when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_sync('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_sync', 'minimal')
        expect(config).not_to have_key('filter_secret_value')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_sync('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_sync', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_sync('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_rotated_secret_sync', 'minimal')
        expect(config).not_to have_key('namespace')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_sync('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_rotated_secret_sync', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['remote_secret_name']).to be_a(String)
        expect(config['usc_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_rotated_secret_sync('first', required_attrs)
        synth.akeyless_rotated_secret_sync('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_rotated_secret_sync')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_rotated_secret_sync,
    method: :akeyless_rotated_secret_sync,
    required_attrs: { name: 'test-value', remote_secret_name: 'test-value', usc_name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
