# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_auth_method_cert resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessAuthMethodCert do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', unique_identifier: 'test-value' } }

  describe ':akeyless_auth_method_cert' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'test')
        validate_required_attributes(config, [:name, :unique_identifier])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_auth_method_cert('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_auth_method_cert)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_auth_method_cert('test', required_attrs)

        expect(ref.id).to eq("${akeyless_auth_method_cert.test.id}")
        expect(ref.access_id).to eq("${akeyless_auth_method_cert.test.access_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'test')
        expect(config).not_to have_key('access_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ access_expires: 3.14, audit_logs_claims: ['test-value'], bound_common_names: ['test-value'], bound_dns_sans: ['test-value'], bound_email_sans: ['test-value'], bound_extensions: ['test-value'], bound_ips: ['test-value'], bound_organizational_units: ['test-value'], bound_uri_sans: ['test-value'], certificate_data: 'test-value', delete_protection: 'test-value', force_sub_claims: true, gw_bound_ips: ['test-value'], jwt_ttl: 3.14, revoked_cert_ids: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'full')
        expect(config).to have_key('access_expires')
        expect(config).to have_key('audit_logs_claims')
        expect(config).to have_key('bound_common_names')
        expect(config).to have_key('bound_dns_sans')
        expect(config).to have_key('bound_email_sans')
        expect(config).to have_key('bound_extensions')
        expect(config).to have_key('bound_ips')
        expect(config).to have_key('bound_organizational_units')
        expect(config).to have_key('bound_uri_sans')
        expect(config).to have_key('certificate_data')
        expect(config).to have_key('delete_protection')
        expect(config).to have_key('force_sub_claims')
        expect(config).to have_key('gw_bound_ips')
        expect(config).to have_key('jwt_ttl')
        expect(config).to have_key('revoked_cert_ids')
      end
    end

    context 'optional attributes' do
      it 'includes access_expires when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('opt', required_attrs.merge(access_expires: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'opt')
        expect(config).to have_key('access_expires')
      end

      it 'omits access_expires when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'minimal')
        expect(config).not_to have_key('access_expires')
      end
      it 'includes audit_logs_claims when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('opt', required_attrs.merge(audit_logs_claims: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'opt')
        expect(config).to have_key('audit_logs_claims')
      end

      it 'omits audit_logs_claims when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'minimal')
        expect(config).not_to have_key('audit_logs_claims')
      end
      it 'includes bound_common_names when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('opt', required_attrs.merge(bound_common_names: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'opt')
        expect(config).to have_key('bound_common_names')
      end

      it 'omits bound_common_names when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'minimal')
        expect(config).not_to have_key('bound_common_names')
      end
      it 'includes bound_dns_sans when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('opt', required_attrs.merge(bound_dns_sans: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'opt')
        expect(config).to have_key('bound_dns_sans')
      end

      it 'omits bound_dns_sans when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'minimal')
        expect(config).not_to have_key('bound_dns_sans')
      end
      it 'includes bound_email_sans when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('opt', required_attrs.merge(bound_email_sans: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'opt')
        expect(config).to have_key('bound_email_sans')
      end

      it 'omits bound_email_sans when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'minimal')
        expect(config).not_to have_key('bound_email_sans')
      end
      it 'includes bound_extensions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('opt', required_attrs.merge(bound_extensions: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'opt')
        expect(config).to have_key('bound_extensions')
      end

      it 'omits bound_extensions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'minimal')
        expect(config).not_to have_key('bound_extensions')
      end
      it 'includes bound_ips when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('opt', required_attrs.merge(bound_ips: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'opt')
        expect(config).to have_key('bound_ips')
      end

      it 'omits bound_ips when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'minimal')
        expect(config).not_to have_key('bound_ips')
      end
      it 'includes bound_organizational_units when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('opt', required_attrs.merge(bound_organizational_units: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'opt')
        expect(config).to have_key('bound_organizational_units')
      end

      it 'omits bound_organizational_units when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'minimal')
        expect(config).not_to have_key('bound_organizational_units')
      end
      it 'includes bound_uri_sans when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('opt', required_attrs.merge(bound_uri_sans: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'opt')
        expect(config).to have_key('bound_uri_sans')
      end

      it 'omits bound_uri_sans when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'minimal')
        expect(config).not_to have_key('bound_uri_sans')
      end
      it 'includes certificate_data when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('opt', required_attrs.merge(certificate_data: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'opt')
        expect(config).to have_key('certificate_data')
      end

      it 'omits certificate_data when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'minimal')
        expect(config).not_to have_key('certificate_data')
      end
      it 'includes delete_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('opt', required_attrs.merge(delete_protection: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'opt')
        expect(config).to have_key('delete_protection')
      end

      it 'omits delete_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'minimal')
        expect(config).not_to have_key('delete_protection')
      end
      it 'includes force_sub_claims when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('opt', required_attrs.merge(force_sub_claims: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'opt')
        expect(config).to have_key('force_sub_claims')
      end

      it 'omits force_sub_claims when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'minimal')
        expect(config).not_to have_key('force_sub_claims')
      end
      it 'includes gw_bound_ips when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('opt', required_attrs.merge(gw_bound_ips: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'opt')
        expect(config).to have_key('gw_bound_ips')
      end

      it 'omits gw_bound_ips when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'minimal')
        expect(config).not_to have_key('gw_bound_ips')
      end
      it 'includes jwt_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('opt', required_attrs.merge(jwt_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'opt')
        expect(config).to have_key('jwt_ttl')
      end

      it 'omits jwt_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'minimal')
        expect(config).not_to have_key('jwt_ttl')
      end
      it 'includes revoked_cert_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('opt', required_attrs.merge(revoked_cert_ids: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'opt')
        expect(config).to have_key('revoked_cert_ids')
      end

      it 'omits revoked_cert_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'minimal')
        expect(config).not_to have_key('revoked_cert_ids')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts force_sub_claims=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(force_sub_claims: val)
          synth.akeyless_auth_method_cert("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_auth_method_cert', "bool_#{val}")
          expect(config['force_sub_claims']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_auth_method_cert', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['unique_identifier']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_auth_method_cert('first', required_attrs)
        synth.akeyless_auth_method_cert('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_auth_method_cert')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_auth_method_cert,
    method: :akeyless_auth_method_cert,
    required_attrs: { name: 'test-value', unique_identifier: 'test-value' },
    expected_outputs: [:id, :access_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:force_sub_claims]
end
