# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_target_github resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessTargetGithub do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':akeyless_target_github' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_github('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_target_github', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_target_github('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_target_github)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_target_github('test', required_attrs)

        expect(ref.id).to eq("${akeyless_target_github.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', github_app_id: 3.14, github_app_private_key: 'test-value', github_base_url: 'test-value', key: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_github('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_target_github', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('github_app_id')
        expect(config).to have_key('github_app_private_key')
        expect(config).to have_key('github_base_url')
        expect(config).to have_key('key')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_github('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_github', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_github('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_github', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes github_app_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_github('opt', required_attrs.merge(github_app_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_github', 'opt')
        expect(config).to have_key('github_app_id')
      end

      it 'omits github_app_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_github('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_github', 'minimal')
        expect(config).not_to have_key('github_app_id')
      end
      it 'includes github_app_private_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_github('opt', required_attrs.merge(github_app_private_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_github', 'opt')
        expect(config).to have_key('github_app_private_key')
      end

      it 'omits github_app_private_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_github('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_github', 'minimal')
        expect(config).not_to have_key('github_app_private_key')
      end
      it 'includes github_base_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_github('opt', required_attrs.merge(github_base_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_github', 'opt')
        expect(config).to have_key('github_base_url')
      end

      it 'omits github_base_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_github('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_github', 'minimal')
        expect(config).not_to have_key('github_base_url')
      end
      it 'includes key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_github('opt', required_attrs.merge(key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_github', 'opt')
        expect(config).to have_key('key')
      end

      it 'omits key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_github('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_github', 'minimal')
        expect(config).not_to have_key('key')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_github('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_target_github', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_github('first', required_attrs)
        synth.akeyless_target_github('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_target_github')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_target_github,
    method: :akeyless_target_github,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
