# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_producer_rdp resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessProducerRdp do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':akeyless_producer_rdp' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_producer_rdp('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_producer_rdp)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_producer_rdp('test', required_attrs)

        expect(ref.id).to eq("${akeyless_producer_rdp.test.id}")
        expect(ref.secure_access_web).to eq("${akeyless_producer_rdp.test.secure_access_web}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'test')
        expect(config).not_to have_key('secure_access_web')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ fixed_user_only: 'test-value', producer_encryption_key_name: 'test-value', rdp_admin_name: 'test-value', rdp_admin_pwd: 'test-value', rdp_host_name: 'test-value', rdp_host_port: 'test-value', rdp_user_groups: 'test-value', secure_access_allow_external_user: true, secure_access_enable: 'test-value', secure_access_host: ['test-value'], secure_access_rdp_domain: 'test-value', secure_access_rdp_user: 'test-value', secure_access_web: true, tags: ['test-value'], target_name: 'test-value', user_ttl: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'full')
        expect(config).to have_key('fixed_user_only')
        expect(config).to have_key('producer_encryption_key_name')
        expect(config).to have_key('rdp_admin_name')
        expect(config).to have_key('rdp_admin_pwd')
        expect(config).to have_key('rdp_host_name')
        expect(config).to have_key('rdp_host_port')
        expect(config).to have_key('rdp_user_groups')
        expect(config).to have_key('secure_access_allow_external_user')
        expect(config).to have_key('secure_access_enable')
        expect(config).to have_key('secure_access_host')
        expect(config).to have_key('secure_access_rdp_domain')
        expect(config).to have_key('secure_access_rdp_user')
        expect(config).to have_key('secure_access_web')
        expect(config).to have_key('tags')
        expect(config).to have_key('target_name')
        expect(config).to have_key('user_ttl')
      end
    end

    context 'optional attributes' do
      it 'includes fixed_user_only when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('opt', required_attrs.merge(fixed_user_only: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'opt')
        expect(config).to have_key('fixed_user_only')
      end

      it 'omits fixed_user_only when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'minimal')
        expect(config).not_to have_key('fixed_user_only')
      end
      it 'includes producer_encryption_key_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('opt', required_attrs.merge(producer_encryption_key_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'opt')
        expect(config).to have_key('producer_encryption_key_name')
      end

      it 'omits producer_encryption_key_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'minimal')
        expect(config).not_to have_key('producer_encryption_key_name')
      end
      it 'includes rdp_admin_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('opt', required_attrs.merge(rdp_admin_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'opt')
        expect(config).to have_key('rdp_admin_name')
      end

      it 'omits rdp_admin_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'minimal')
        expect(config).not_to have_key('rdp_admin_name')
      end
      it 'includes rdp_admin_pwd when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('opt', required_attrs.merge(rdp_admin_pwd: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'opt')
        expect(config).to have_key('rdp_admin_pwd')
      end

      it 'omits rdp_admin_pwd when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'minimal')
        expect(config).not_to have_key('rdp_admin_pwd')
      end
      it 'includes rdp_host_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('opt', required_attrs.merge(rdp_host_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'opt')
        expect(config).to have_key('rdp_host_name')
      end

      it 'omits rdp_host_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'minimal')
        expect(config).not_to have_key('rdp_host_name')
      end
      it 'includes rdp_host_port when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('opt', required_attrs.merge(rdp_host_port: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'opt')
        expect(config).to have_key('rdp_host_port')
      end

      it 'omits rdp_host_port when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'minimal')
        expect(config).not_to have_key('rdp_host_port')
      end
      it 'includes rdp_user_groups when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('opt', required_attrs.merge(rdp_user_groups: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'opt')
        expect(config).to have_key('rdp_user_groups')
      end

      it 'omits rdp_user_groups when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'minimal')
        expect(config).not_to have_key('rdp_user_groups')
      end
      it 'includes secure_access_allow_external_user when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('opt', required_attrs.merge(secure_access_allow_external_user: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'opt')
        expect(config).to have_key('secure_access_allow_external_user')
      end

      it 'omits secure_access_allow_external_user when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'minimal')
        expect(config).not_to have_key('secure_access_allow_external_user')
      end
      it 'includes secure_access_enable when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('opt', required_attrs.merge(secure_access_enable: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'opt')
        expect(config).to have_key('secure_access_enable')
      end

      it 'omits secure_access_enable when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'minimal')
        expect(config).not_to have_key('secure_access_enable')
      end
      it 'includes secure_access_host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('opt', required_attrs.merge(secure_access_host: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'opt')
        expect(config).to have_key('secure_access_host')
      end

      it 'omits secure_access_host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'minimal')
        expect(config).not_to have_key('secure_access_host')
      end
      it 'includes secure_access_rdp_domain when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('opt', required_attrs.merge(secure_access_rdp_domain: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'opt')
        expect(config).to have_key('secure_access_rdp_domain')
      end

      it 'omits secure_access_rdp_domain when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'minimal')
        expect(config).not_to have_key('secure_access_rdp_domain')
      end
      it 'includes secure_access_rdp_user when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('opt', required_attrs.merge(secure_access_rdp_user: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'opt')
        expect(config).to have_key('secure_access_rdp_user')
      end

      it 'omits secure_access_rdp_user when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'minimal')
        expect(config).not_to have_key('secure_access_rdp_user')
      end
      it 'includes secure_access_web when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('opt', required_attrs.merge(secure_access_web: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'opt')
        expect(config).to have_key('secure_access_web')
      end

      it 'omits secure_access_web when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'minimal')
        expect(config).not_to have_key('secure_access_web')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes target_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('opt', required_attrs.merge(target_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'opt')
        expect(config).to have_key('target_name')
      end

      it 'omits target_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'minimal')
        expect(config).not_to have_key('target_name')
      end
      it 'includes user_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('opt', required_attrs.merge(user_ttl: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'opt')
        expect(config).to have_key('user_ttl')
      end

      it 'omits user_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'minimal')
        expect(config).not_to have_key('user_ttl')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts secure_access_allow_external_user=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(secure_access_allow_external_user: val)
          synth.akeyless_producer_rdp("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_producer_rdp', "bool_#{val}")
          expect(config['secure_access_allow_external_user']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts secure_access_web=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(secure_access_web: val)
          synth.akeyless_producer_rdp("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_producer_rdp', "bool_#{val}")
          expect(config['secure_access_web']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_producer_rdp', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_producer_rdp('first', required_attrs)
        synth.akeyless_producer_rdp('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_producer_rdp')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_producer_rdp,
    method: :akeyless_producer_rdp,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :secure_access_web],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:secure_access_allow_external_user, :secure_access_web]
end
