# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_tokenizer resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessTokenizer do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', template_type: 'test-value' } }

  describe ':akeyless_tokenizer' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'test')
        validate_required_attributes(config, [:name, :template_type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_tokenizer('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_tokenizer)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_tokenizer('test', required_attrs)

        expect(ref.id).to eq("${akeyless_tokenizer.test.id}")
        expect(ref.tweak).to eq("${akeyless_tokenizer.test.tweak}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_tokenizer', 'test')
        expect(config).not_to have_key('tweak')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ alphabet: 'test-value', decoding_template: 'test-value', delete_protection: 'test-value', description: 'test-value', encoding_template: 'test-value', encryption_key_name: 'test-value', pattern: 'test-value', tag: ['test-value'], tokenizer_type: 'test-value', tweak_type: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_tokenizer', 'full')
        expect(config).to have_key('alphabet')
        expect(config).to have_key('decoding_template')
        expect(config).to have_key('delete_protection')
        expect(config).to have_key('description')
        expect(config).to have_key('encoding_template')
        expect(config).to have_key('encryption_key_name')
        expect(config).to have_key('pattern')
        expect(config).to have_key('tag')
        expect(config).to have_key('tokenizer_type')
        expect(config).to have_key('tweak_type')
      end
    end

    context 'optional attributes' do
      it 'includes alphabet when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('opt', required_attrs.merge(alphabet: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'opt')
        expect(config).to have_key('alphabet')
      end

      it 'omits alphabet when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'minimal')
        expect(config).not_to have_key('alphabet')
      end
      it 'includes decoding_template when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('opt', required_attrs.merge(decoding_template: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'opt')
        expect(config).to have_key('decoding_template')
      end

      it 'omits decoding_template when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'minimal')
        expect(config).not_to have_key('decoding_template')
      end
      it 'includes delete_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('opt', required_attrs.merge(delete_protection: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'opt')
        expect(config).to have_key('delete_protection')
      end

      it 'omits delete_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'minimal')
        expect(config).not_to have_key('delete_protection')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes encoding_template when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('opt', required_attrs.merge(encoding_template: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'opt')
        expect(config).to have_key('encoding_template')
      end

      it 'omits encoding_template when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'minimal')
        expect(config).not_to have_key('encoding_template')
      end
      it 'includes encryption_key_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('opt', required_attrs.merge(encryption_key_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'opt')
        expect(config).to have_key('encryption_key_name')
      end

      it 'omits encryption_key_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'minimal')
        expect(config).not_to have_key('encryption_key_name')
      end
      it 'includes pattern when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('opt', required_attrs.merge(pattern: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'opt')
        expect(config).to have_key('pattern')
      end

      it 'omits pattern when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'minimal')
        expect(config).not_to have_key('pattern')
      end
      it 'includes tag when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('opt', required_attrs.merge(tag: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'opt')
        expect(config).to have_key('tag')
      end

      it 'omits tag when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'minimal')
        expect(config).not_to have_key('tag')
      end
      it 'includes tokenizer_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('opt', required_attrs.merge(tokenizer_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'opt')
        expect(config).to have_key('tokenizer_type')
      end

      it 'omits tokenizer_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'minimal')
        expect(config).not_to have_key('tokenizer_type')
      end
      it 'includes tweak_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('opt', required_attrs.merge(tweak_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'opt')
        expect(config).to have_key('tweak_type')
      end

      it 'omits tweak_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_tokenizer', 'minimal')
        expect(config).not_to have_key('tweak_type')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_tokenizer', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['template_type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_tokenizer('first', required_attrs)
        synth.akeyless_tokenizer('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_tokenizer')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_tokenizer,
    method: :akeyless_tokenizer,
    required_attrs: { name: 'test-value', template_type: 'test-value' },
    expected_outputs: [:id, :tweak],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
