# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_dynamic_secret_gcp resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessDynamicSecretGcp do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':akeyless_dynamic_secret_gcp' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_dynamic_secret_gcp('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_dynamic_secret_gcp)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_dynamic_secret_gcp('test', required_attrs)

        expect(ref.id).to eq("${akeyless_dynamic_secret_gcp.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ access_type: 'test-value', custom_username_template: 'test-value', delete_protection: 'test-value', encryption_key_name: 'test-value', fixed_user_claim_keyname: 'test-value', gcp_cred_type: 'test-value', gcp_key: 'test-value', gcp_key_algo: 'test-value', gcp_sa_email: 'test-value', gcp_token_scopes: 'test-value', project_id: 'test-value', role_binding: 'test-value', role_names: 'test-value', service_account_type: 'test-value', tags: ['test-value'], target_name: 'test-value', user_ttl: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'full')
        expect(config).to have_key('access_type')
        expect(config).to have_key('custom_username_template')
        expect(config).to have_key('delete_protection')
        expect(config).to have_key('encryption_key_name')
        expect(config).to have_key('fixed_user_claim_keyname')
        expect(config).to have_key('gcp_cred_type')
        expect(config).to have_key('gcp_key')
        expect(config).to have_key('gcp_key_algo')
        expect(config).to have_key('gcp_sa_email')
        expect(config).to have_key('gcp_token_scopes')
        expect(config).to have_key('project_id')
        expect(config).to have_key('role_binding')
        expect(config).to have_key('role_names')
        expect(config).to have_key('service_account_type')
        expect(config).to have_key('tags')
        expect(config).to have_key('target_name')
        expect(config).to have_key('user_ttl')
      end
    end

    context 'optional attributes' do
      it 'includes access_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(access_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('access_type')
      end

      it 'omits access_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('access_type')
      end
      it 'includes custom_username_template when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(custom_username_template: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('custom_username_template')
      end

      it 'omits custom_username_template when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('custom_username_template')
      end
      it 'includes delete_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(delete_protection: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('delete_protection')
      end

      it 'omits delete_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('delete_protection')
      end
      it 'includes encryption_key_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(encryption_key_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('encryption_key_name')
      end

      it 'omits encryption_key_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('encryption_key_name')
      end
      it 'includes fixed_user_claim_keyname when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(fixed_user_claim_keyname: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('fixed_user_claim_keyname')
      end

      it 'omits fixed_user_claim_keyname when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('fixed_user_claim_keyname')
      end
      it 'includes gcp_cred_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(gcp_cred_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('gcp_cred_type')
      end

      it 'omits gcp_cred_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('gcp_cred_type')
      end
      it 'includes gcp_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(gcp_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('gcp_key')
      end

      it 'omits gcp_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('gcp_key')
      end
      it 'includes gcp_key_algo when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(gcp_key_algo: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('gcp_key_algo')
      end

      it 'omits gcp_key_algo when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('gcp_key_algo')
      end
      it 'includes gcp_sa_email when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(gcp_sa_email: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('gcp_sa_email')
      end

      it 'omits gcp_sa_email when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('gcp_sa_email')
      end
      it 'includes gcp_token_scopes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(gcp_token_scopes: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('gcp_token_scopes')
      end

      it 'omits gcp_token_scopes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('gcp_token_scopes')
      end
      it 'includes project_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(project_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('project_id')
      end

      it 'omits project_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('project_id')
      end
      it 'includes role_binding when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(role_binding: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('role_binding')
      end

      it 'omits role_binding when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('role_binding')
      end
      it 'includes role_names when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(role_names: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('role_names')
      end

      it 'omits role_names when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('role_names')
      end
      it 'includes service_account_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(service_account_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('service_account_type')
      end

      it 'omits service_account_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('service_account_type')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes target_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(target_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('target_name')
      end

      it 'omits target_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('target_name')
      end
      it 'includes user_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('opt', required_attrs.merge(user_ttl: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'opt')
        expect(config).to have_key('user_ttl')
      end

      it 'omits user_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'minimal')
        expect(config).not_to have_key('user_ttl')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_dynamic_secret_gcp', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_dynamic_secret_gcp('first', required_attrs)
        synth.akeyless_dynamic_secret_gcp('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_dynamic_secret_gcp')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_dynamic_secret_gcp,
    method: :akeyless_dynamic_secret_gcp,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
