# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_target_ssh resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessTargetSsh do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':akeyless_target_ssh' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_target_ssh('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_target_ssh)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_target_ssh('test', required_attrs)

        expect(ref.id).to eq("${akeyless_target_ssh.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', host: 'test-value', key: 'test-value', port: 'test-value', private_key: 'test-value', private_key_password: 'test-value', ssh_password: 'test-value', ssh_username: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_target_ssh', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('host')
        expect(config).to have_key('key')
        expect(config).to have_key('port')
        expect(config).to have_key('private_key')
        expect(config).to have_key('private_key_password')
        expect(config).to have_key('ssh_password')
        expect(config).to have_key('ssh_username')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('opt', required_attrs.merge(host: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'opt')
        expect(config).to have_key('host')
      end

      it 'omits host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'minimal')
        expect(config).not_to have_key('host')
      end
      it 'includes key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('opt', required_attrs.merge(key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'opt')
        expect(config).to have_key('key')
      end

      it 'omits key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'minimal')
        expect(config).not_to have_key('key')
      end
      it 'includes port when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('opt', required_attrs.merge(port: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'opt')
        expect(config).to have_key('port')
      end

      it 'omits port when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'minimal')
        expect(config).not_to have_key('port')
      end
      it 'includes private_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('opt', required_attrs.merge(private_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'opt')
        expect(config).to have_key('private_key')
      end

      it 'omits private_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'minimal')
        expect(config).not_to have_key('private_key')
      end
      it 'includes private_key_password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('opt', required_attrs.merge(private_key_password: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'opt')
        expect(config).to have_key('private_key_password')
      end

      it 'omits private_key_password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'minimal')
        expect(config).not_to have_key('private_key_password')
      end
      it 'includes ssh_password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('opt', required_attrs.merge(ssh_password: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'opt')
        expect(config).to have_key('ssh_password')
      end

      it 'omits ssh_password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'minimal')
        expect(config).not_to have_key('ssh_password')
      end
      it 'includes ssh_username when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('opt', required_attrs.merge(ssh_username: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'opt')
        expect(config).to have_key('ssh_username')
      end

      it 'omits ssh_username when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_ssh', 'minimal')
        expect(config).not_to have_key('ssh_username')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_target_ssh', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_ssh('first', required_attrs)
        synth.akeyless_target_ssh('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_target_ssh')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_target_ssh,
    method: :akeyless_target_ssh,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
