# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a akeyless_target_db resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AkeylessTargetDb do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { db_type: 'test-value', name: 'test-value' } }

  describe ':akeyless_target_db' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'akeyless_target_db', 'test')
        validate_required_attributes(config, [:db_type, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_target_db('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:akeyless_target_db)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.akeyless_target_db('test', required_attrs)

        expect(ref.id).to eq("${akeyless_target_db.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ db_name: 'test-value', db_server_certificates: 'test-value', db_server_name: 'test-value', description: 'test-value', host: 'test-value', key: 'test-value', mongodb_atlas: true, mongodb_atlas_api_private_key: 'test-value', mongodb_atlas_api_public_key: 'test-value', mongodb_atlas_project_id: 'test-value', mongodb_default_auth_db: 'test-value', mongodb_uri_options: 'test-value', oracle_service_name: 'test-value', port: 'test-value', pwd: 'test-value', snowflake_account: 'test-value', ssl: true, ssl_certificate: 'test-value', user_name: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_target_db', 'full')
        expect(config).to have_key('db_name')
        expect(config).to have_key('db_server_certificates')
        expect(config).to have_key('db_server_name')
        expect(config).to have_key('description')
        expect(config).to have_key('host')
        expect(config).to have_key('key')
        expect(config).to have_key('mongodb_atlas')
        expect(config).to have_key('mongodb_atlas_api_private_key')
        expect(config).to have_key('mongodb_atlas_api_public_key')
        expect(config).to have_key('mongodb_atlas_project_id')
        expect(config).to have_key('mongodb_default_auth_db')
        expect(config).to have_key('mongodb_uri_options')
        expect(config).to have_key('oracle_service_name')
        expect(config).to have_key('port')
        expect(config).to have_key('pwd')
        expect(config).to have_key('snowflake_account')
        expect(config).to have_key('ssl')
        expect(config).to have_key('ssl_certificate')
        expect(config).to have_key('user_name')
      end
    end

    context 'optional attributes' do
      it 'includes db_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(db_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('db_name')
      end

      it 'omits db_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('db_name')
      end
      it 'includes db_server_certificates when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(db_server_certificates: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('db_server_certificates')
      end

      it 'omits db_server_certificates when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('db_server_certificates')
      end
      it 'includes db_server_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(db_server_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('db_server_name')
      end

      it 'omits db_server_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('db_server_name')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(host: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('host')
      end

      it 'omits host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('host')
      end
      it 'includes key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('key')
      end

      it 'omits key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('key')
      end
      it 'includes mongodb_atlas when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(mongodb_atlas: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('mongodb_atlas')
      end

      it 'omits mongodb_atlas when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('mongodb_atlas')
      end
      it 'includes mongodb_atlas_api_private_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(mongodb_atlas_api_private_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('mongodb_atlas_api_private_key')
      end

      it 'omits mongodb_atlas_api_private_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('mongodb_atlas_api_private_key')
      end
      it 'includes mongodb_atlas_api_public_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(mongodb_atlas_api_public_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('mongodb_atlas_api_public_key')
      end

      it 'omits mongodb_atlas_api_public_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('mongodb_atlas_api_public_key')
      end
      it 'includes mongodb_atlas_project_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(mongodb_atlas_project_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('mongodb_atlas_project_id')
      end

      it 'omits mongodb_atlas_project_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('mongodb_atlas_project_id')
      end
      it 'includes mongodb_default_auth_db when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(mongodb_default_auth_db: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('mongodb_default_auth_db')
      end

      it 'omits mongodb_default_auth_db when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('mongodb_default_auth_db')
      end
      it 'includes mongodb_uri_options when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(mongodb_uri_options: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('mongodb_uri_options')
      end

      it 'omits mongodb_uri_options when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('mongodb_uri_options')
      end
      it 'includes oracle_service_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(oracle_service_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('oracle_service_name')
      end

      it 'omits oracle_service_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('oracle_service_name')
      end
      it 'includes port when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(port: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('port')
      end

      it 'omits port when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('port')
      end
      it 'includes pwd when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(pwd: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('pwd')
      end

      it 'omits pwd when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('pwd')
      end
      it 'includes snowflake_account when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(snowflake_account: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('snowflake_account')
      end

      it 'omits snowflake_account when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('snowflake_account')
      end
      it 'includes ssl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(ssl: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('ssl')
      end

      it 'omits ssl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('ssl')
      end
      it 'includes ssl_certificate when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(ssl_certificate: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('ssl_certificate')
      end

      it 'omits ssl_certificate when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('ssl_certificate')
      end
      it 'includes user_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('opt', required_attrs.merge(user_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'opt')
        expect(config).to have_key('user_name')
      end

      it 'omits user_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'akeyless_target_db', 'minimal')
        expect(config).not_to have_key('user_name')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts mongodb_atlas=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(mongodb_atlas: val)
          synth.akeyless_target_db("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_target_db', "bool_#{val}")
          expect(config['mongodb_atlas']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts ssl=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ssl: val)
          synth.akeyless_target_db("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'akeyless_target_db', "bool_#{val}")
          expect(config['ssl']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'akeyless_target_db', 'typed')
        expect(config['db_type']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.akeyless_target_db('first', required_attrs)
        synth.akeyless_target_db('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'akeyless_target_db')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :akeyless_target_db,
    method: :akeyless_target_db,
    required_attrs: { db_type: 'test-value', name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:mongodb_atlas, :ssl]
end
