# Code generated by pangea-forge.
# InSpec profile for verifying akeyless_auth_method_aws_iam infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AKEYLESS_TOKEN and AKEYLESS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/akeyless_auth_method_aws_iam/ -t akeyless://

control 'akeyless_auth_method_aws_iam-exists' do
  impact 1.0
  title 'Manages a akeyless_auth_method_aws_iam resource'
  desc 'Verify that the akeyless_auth_method_aws_iam resource exists and has expected properties'

  describe akeyless_auth_method_aws_iam(name: attribute('id')) do
    it { should exist }
    its('bound_aws_account_id') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
